### ISSUE TITLE
DNSSEC für .fffd

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#1]

**Comment by reissmann** [comment]
Ich schliesse dieses Issue, da ich keine Moeglichkeit sehe, das sinnvoll umzusetzen. DNSSEC fuer eine den gaengigen Browsern nicht offiziell bekannte TLD ist zwar grundsaetzlich moeglich, wird aber zu Problemen fuehren.

Alternative: Wir koennten statt .fffd eine andere Domain nutzen. Beispielsweise fffd.de
