### ISSUE TITLE
Keyupload funktioniert bei KVM Image nicht

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/orga#100]
Das Scipt für den Keyupload funktioniert auf dem bereitgestelltem KVM Image nicht.

Der Befehl `sed 's/://g' /lib/gluon/core/sysconfig/primary_mac` des Uploadscripts liefert folgenden Fehler `sed: /lib/gluon/core/sysconfig/primary_mac: No such file or directory`

**Comment by mortzel** [comment]
Please review the Pull Request freifunk-fulda/fffd-packages/pull/3

**Comment by fooker** [comment]
`/lib/gluon/core/sysconfig/primary_mac` sollte von einem update-script angelegt werden.

Kannst du auf dem system mal versuchen das Script `/lib/gluon/upgrade/010-primary-mac` auszuführen?

Das fehlen der Datei beteifft nicht nur den Key-Upload, sondern auch einige andere sachen, wie z.B. alfred-announce.

**Comment by mortzel** [comment]
Wenn man das Script manuell ausführt wird die Datei `/lib/gluon/core/sysconfig/primary_mac` erstellt.

**Comment by fooker** [comment]
War zum Zeitpunk des Updates / der Installation das Netzwerk-Interface schon in der VM konfiguriert?

**Comment by mortzel** [comment]
Ja die VM hatte zum Zeitpunkt des ersten Starts bereits ein Netzwerinterface.

**Comment by fooker** [comment]
Ich hab das erade versucht nachzustellen. Bei mir wir die Datei korrekt angelegt und gefüllt. Kannst du mir mal einen Dump der VM-Config zukommen lassen?

**Comment by mortzel** [comment]
Es sieht so aus, als ob das Problem nur auftaucht, wenn bei dem ersten Starten der VM nur ein Netzwerkinterface aktiv ist.
