### ISSUE TITLE
Proxy fuer OPKG

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#101]
Auf den Knoten kann derzeit der Paketmanager nicht verwendet werden, da packages.openwrt.org nur per IPv4 erreichbar ist, die Knoten aber keine IPv4 Adresse haben.

In der kommenden Firmware sollte folgende direktive hinzugefuegt werden:

```
opkg = {
    openwrt = 'http://opkg.services.fffd/openwrt/%n/%v/%S/packages',
    extra = {
        modules = 'http://opkg.services.fffd/modules/gluon-%GS-%GR/%S',
    },
}
```

Darueber hinaus muss ein Proxy unter opkg.services.fffd aufgesetzt werden.

**Comment by mortzel** [comment]
Proxy wurde auf dem Server 'srv01.fulda.freifunk.net' eingerichtet und ist im Freifunk-Netz unter dem DNS Eintrag opkg.services.fffd erreichbar.

Die Gluon Module werden dort noch nicht bereitgestellt, da dies erst ab Version 2015.2 unterstützt wird.

**Comment by fooker** [comment]
According PR: https://github.com/freifunk-fulda/site-fffd/pull/26

**Comment by fooker** [comment]
Merged.
