### ISSUE TITLE
Firmware images should contain branch, commit and build information

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#102]
Currently, the build number can only be resolved to a branch or an commit ID by looking up the ID in the build system. The build system may drop old build logs at any time.

To make a build more trackable, the created firmware folder should contain a file `build` containing the build date, the commit ID, the branch name and other information in a format similar to the manifest header.

**Comment by fooker** [comment]
Fixed by https://github.com/freifunk-fulda/site-fffd/pull/22.

**Comment by fooker** [comment]
Jenkins was modified to create and push a tag with the format `build/${BUILD_ID}` for each build.

**Comment by mortzel** [comment]
The push from jenkins should be done with a new GitHub user for jenkins and not with fooker's account.

**Comment by fooker** [comment]
It's done with a deploy key based on the jenkins ssh key (wich is the same we use for uploading of the images). Thia key is configured per project and is always assigned to the user who has configured the key.

**Comment by fooker** [comment]
Seems to work well in development.
