### ISSUE TITLE
Fix ffmap-backend/nodes.json

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/orga#106]
In letzter Zeit häufen sich die Probleme mit dem ffmap-backend bzw. einer defekten nodes.json.

Da bei jedem Auftreten des Fehlers der Meshviwer nicht funktioniert und unser Monitoring keine Daten sammeln kann, sollte dieses Problem dirgend behoben werden.

**Comment by fooker** [comment]
Looks like there is a bug in python2 json API trigered by very long lines. I've changed the code to generate formated jason. Seems to work stable since two days.

**Comment by mortzel** [comment]
Ich hab nun ffmap-backend auf srv1 mal auf den aktuellen master branch von ffnord/ffmap-backend gemacht und unsere Anpassungen eingepflegt.

Das ganze müsste jedoch noch in unser Repo gemerged werden.

**Comment by mortzel** [comment]
Wurde durch Hopglasses ersetzt
