### ISSUE TITLE
Set peer limit to 1

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#107]
In the site.conf, please set limit = 1 in the fastd_mesh_vpn section.

There is no real advantage of having nodes connect to two gateways. By having the vpn limited to one gateway, (I hope) a better traffic distribution among gateways could be achieved. If the selected gateway goes offline, a new connection should be established automatically.

**Comment by fooker** [comment]
Thinking about this a lot: there is an advantage of having multiple connections if a node provides gateway connections for a local cloud of nodes. In this case, each node in the local cloud can choose a different gateway which leads to better load balancing.

**Comment by SISheogorath** [comment]
Some links and analyses:
https://forum.freifunk.net/t/fastd-tunnel-anzahl-limit-2-oder-lieber-5-traffic-impact/10280/11
https://forum.freifunk.net/t/analyse-zur-anzahl-der-tunnel/5971

**Comment by fooker** [comment]
According pull-request: https://github.com/freifunk-fulda/site-fffd/pull/24

**Comment by fooker** [comment]
Result of discussion: we reduce the limit to 1 and increase it manually on big clouds.

**Comment by fooker** [comment]
Merged.
