### ISSUE TITLE
Automatic refresh of fffd-nodes-backbone on all systems

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#108]
When new backbone systems are added to the fffd-nodes-backbone repo, the repo needs to get refreshed on all systems

**Comment by mortzel** [comment]
Use the script `fffd-utils/update-repo.cron` which is allready in our repos.

**Comment by Jo-Jo0** [comment]
Repo is updated with every salt run on the system. This should be enough, because this repo isn't changed that often.
