### ISSUE TITLE
Fix routing on all systems

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#109]
Routing is broken on many systems. Just use mtr to see yourself.

**Comment by reissmann** [comment]
Beispiel:

18:12:33.321059 IP 172.20.46.10 > nms.services.fffd: ICMP echo request, id 28522, seq 57730, length 44
18:12:33.321074 IP gw04.services.fffd > 172.20.46.10: ICMP time exceeded in-transit, length 72

**Comment by reissmann** [comment]
Von gw04 kann man srv1 nicht erreichen. Von gw01 aus geht es ...

**Comment by fooker** [comment]
Will be fixed by current work for #143.
