### ISSUE TITLE
Static DHCP

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#110]
Implement a static dhcp mechanism for all the systems, which use static ip addresses. This way, routing and default gw assignment is much easier.

**Comment by mortzel** [comment]
How would that help to fix routing and default gw assignment when having multiple gateways?

**Comment by fooker** [comment]
Batman routes the DHCP request to the"best" gateway. If the gateway goes down, anotherone will be choosen if the lease expires.

## 

-----Original Message-----
