### ISSUE TITLE
Build SSL Cert distribution for fffd.eu domain

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/orga#113]
With our new internal domain `fffd.eu` we can request official certificates for internal use. Because these certificates are for a internal used domain, we need a system to request and distribut these certificates to the user.

**Comment by mortzel** [comment]
A option is to request the certificats with _Let's Encrypt_ and distribut them to the users. But the certificats can only requested from a server which is reachble under this dns record. 

So we need a server with a external ip and a dns wilcard record for all subdomains of _fffd.eu_.

**Comment by SISheogorath** [comment]
a simple way would be someone offers an reverseproxy service to Freifunk network. but we should split the public and private domain part then.

so Let's encrypt works fine
