### ISSUE TITLE
Alfred auf srv1 laeuft nicht

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#115]
Auf srv1 scheinen die Abhaengigkeiten zwischen den Diensten noch viel mehr kaputt zu sein, als auf allen anderen Systemen. Regelmaessig laeuft hier snmpd oder alfred nicht. Das fuehrt dazu, dass dann die Dashboards in Grafana kaputt sind (siehe: https://grafana.fulda.freifunk.net/dashboard/db/freifunk-fulda-nodes)

**Comment by mortzel** [comment]
Eventuell sollte man srv1 mal auf eine anderes System umziehen, da der RAM gut ausgelastet ist und in unregelmäßigen Abständen massive io-waits entstehen.
Hierfür würde sich das alte gw02 oder vielleicht auch gw01 anbeiten.

**Comment by mortzel** [comment]
Mittlerweile wird respondd verwendet
