### ISSUE TITLE
Fix bird.fulda.freifunk.net on srv1.fulda.freifunk.net

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/orga#123]
After the migration the site bird.fulda.freifunk.net does not work.

`
  The site genertes this output in the apache2 error log:
  mod_wsgi (pid=129872): Target WSGI script '/var/www/bird.fulda.freifunk.net/lg.wsgi' cannot be   loaded as Python module.
  mod_wsgi (pid=129872): Exception occurred processing WSGI script '/var/www/bird.fulda.freifunk.net/lg.wsgi'.
  Traceback (most recent call last):
    File "/var/www/bird.fulda.freifunk.net/lg.wsgi", line 8, in <module>
      from lg import app as application
    File "/var/www/bird.fulda.freifunk.net/lg.py", line 25, in <module>
      from urllib import quote, unquote
  [ImportError: cannot import name 'quote'
`

**Comment by fooker** [comment]
Fixed.
