### ISSUE TITLE
Add ips of gateways to site.conf

### ISSUE THREAD

**Issue by Scifire** [freifunk-fulda/orga#124]
If choosing a static ip in a router only ip/sub/gateway is a required field (red) but in our case we need also a manual dns entry. #105

**Comment by reissmann** [comment]
referring to configmode -> expert -> schnittstellen -> static ip

mark dns server as a required field.

**Comment by Noodlesalat** [comment]
Started working on this issue. See [https://git.maglab.space/fffd/site-fffd/tree/issue/124](https://git.maglab.space/fffd/site-fffd/tree/issue/124)

**Comment by Noodlesalat** [comment]
I think its better to add the gateways IP address to the site.conf file. Otherwise we have to fork the gluon-web-network package into fffd-packages...

**Comment by mortzel** [comment]
We will add the gateway ips to the site.conf
