### ISSUE TITLE
Graphen Meshviewer

### ISSUE THREAD

**Issue by Moorviper** [freifunk-fulda/orga#126]
Zur Zeit werden ja keine Graphen im Meshviewer angezeigt:

Um dies zu beheben müsste das folgende Dashboard dupliziert werden mit dem unterschied das man nicht per Node-Namen auswählt sondern per ID

https://grafana.fulda.freifunk.net/dashboard/db/freifunk-fulda-nodes
dupliziert als:
https://grafana.fulda.freifunk.net/dashboard/db/freifunk-fulda-nodes-by-id

In der config. vom meshviewer müsste dann ein:

```
"nodeInfos": [
    {
  "name": "Clients",
  "href": "https://grafana.fulda.freifunk.net/dashboard-solo/db/freifunk-fulda-nodes-by-id?panelId=10&fullscreen&theme=light&var-node={NODE_ID}",
  "thumbnail": "https://grafana.fulda.freifunk.net/render/dashboard-solo/db/freifunk-fulda-nodes-by-id?panelId=10&fullscreen&theme=light&width=528&height=266&var-node={NODE_ID}",
  "caption": "Clients Knoten {NODE_ID}"
},
{
  "name": "Traffic Rates",
  "href": "https://grafana.fulda.freifunk.net/dashboard-solo/db/freifunk-fulda-nodes-by-id?panelId=1&fullscreen&theme=light&var-node={NODE_ID}",
  "thumbnail": "https://grafana.fulda.freifunk.net/render/dashboard-solo/db/freifunk-fulda-nodes-by-id?panelId=1&fullscreen&theme=light&width=528&height=266&var-node={NODE_ID}",
  "caption": "Traffic Rates Knoten {NODE_ID}"
}
```

  ],

reichen damit die Graphen eingeblendet werden.

**Comment by Moorviper** [comment]
für die GW statistic unter Statistiken 
reicht:

```
globalInfos": [
{
"name": "Gateways",
"href": "https://grafana.fulda.freifunk.net/render/dashboard-solo/db/freifunk-fulda-overview?panelId=8&fullscreen",
"thumbnail": "https://grafana.fulda.freifunk.net/render/dashboard-solo/db/freifunk-fulda-overview?panelId=8&fullscreen&theme=light&width=528&height=266",
"caption": "Gateways"
}
],
```

(geht prinzipiell schon ;)

**Comment by fooker** [comment]
Habe mal angefangen zwei entsprechende Dashboards zu bauen. Die globalen Graphen gehen schon.

Die Node ID ist nicht so einfach abzubilden, da der Namespace im graphite im Moment keine Trennung hergibt. Dafür müsste das nodestats.py Script auf folgendes Muster angepasst werden:

```
fffd.
  clients
  nodes.
    total
    online
    by-id.
      $nodeid
        loadavg
        uptime
        clients
        ...
    by-name.
      $hostname
        loadavg
        uptime
        clients
        ...
```

Dafür müssen natürlich auch die Dashboards angepasst werden.

Oder wir finden eine Art Alias von der Variable auf ein Label im grafana - dann können wir nur die node-id verwenden.

**Comment by Moorviper** [comment]
fixed 
Im meshviewer gefixed
