### ISSUE TITLE
Alte SSID's verbleiben nach Firmware-upgrade in config

### ISSUE THREAD

**Issue by Moorviper** [freifunk-fulda/orga#129]
Beispiel:

```
 root@Max-Bahr-wdr3600-3:~# uci show | grep -i ssid | grep -i radio0
 wireless.alias_2_radio0.ssid=fulda.freifunk.net
 wireless.client_radio0.ssid=fulda.freifunk.net
 wireless.mesh_radio0.bssid=00:00:ff:fd:00:11
 wireless.mesh_radio0.ssid=00:00:ff:fd:00:11
 wireless.alias_1_radio0.ssid=freifunk.net
```

**Comment by fooker** [comment]
Das Problem tritt bei Updates von v3 auf v4 auf. Das Update-Script legt nur die benötigten Aliases laut config an, löscht aber Aliase die aus der Config entfernt wurden nicht. Das Update-Script muss entsprechenden angepasst werden.

**Comment by fooker** [comment]
Merged to testing for v4 r1

**Comment by fooker** [comment]
https://github.com/freifunk-fulda/site-fffd/commit/c0ea5425326e840a23a1141ece1302e55a9833a0
