### ISSUE TITLE
Get access to @FreifunkFulda Twitter Account

### ISSUE THREAD

**Issue by Jo-Jo0** [freifunk-fulda/orga#134]
We should get access to the @FreifunkFulda twitter account. Does somebody know, who owns it?

**Comment by Noodlesalat** [comment]
Gibt es hier mittlerweile Updates? Haben wir wieder Zugang zu dem Account? Getwittert wurde längere Zeit ja nichts...
Ich hänge mich mal dran!

**Comment by Jo-Jo0** [comment]
no, nothing new here...
Feel free to work on this

**Comment by menschenpaste** [comment]
Ist wieder als aktives Mitglied integriert 👍

**Comment by fooker** [comment]
Das bedeutet aber immer noch nicht, das mehr als eine Person zugang zu diesem Account haben.

-- 


-----Original Message-----

**Comment by Jo-Jo0** [comment]
Na dann freue ich mich auf intensive Zusammenarbeit. Ich bin am Freitag vermutlich so gegen 21 Uhr im Space und freue mich, dich @menschenpaste dort kennen zu lernen

**Comment by Jo-Jo0** [comment]
Ich lasse den issue noch offen, schließlich ist er nicht erfüllt!

**Comment by Noodlesalat** [comment]
Bitte schließen, Passwort wird ins pass-Repo eingepflegt und an Mitgleider verteilt, die sich um Social Media kümmern wollen.
