### ISSUE TITLE
Wiki eintrag auf Freifunk.net zu FFFD aktualisieren

### ISSUE THREAD

**Issue by Scifire** [freifunk-fulda/orga#136]
Sofern jemand einen Account hat sollte unser Eintrag unter:
https://wiki.freifunk.net/Freifunk_Fulda
einmal aktualisiert werden. Die meisten infos sind fehlerhaft oder veraltet.

**Comment by SISheogorath** [comment]
Habe schonmal ein bisschen was aktualisiert, man könnte es noch erweitern, allerdings sollte das nötigste nun neu gepflegt sein.

**Comment by Jo-Jo0** [comment]
Sind noch ein paar Fehler drin

**Comment by Noodlesalat** [comment]
Fixed. :)
