### ISSUE TITLE
Service dependencies (dhcp und snmp)

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#141]
Die Dienste isc-dhcp-server und snmpd kommen nach einem Neustart nicht hoch, da das Interface an das sie gerne binden moechten (fffd.bat) zu dieser Zeit noch nicht existiert.

Beide systemd services verwenden hintenrum init-Skripte (danke, Debian), weshalb kein unit-file existiert, in das man die Abhaengigkeit einfach eintragen koennte.

**Comment by mortzel** [comment]
Wurde irgendwann gefixt. Läuft mitterweile
