### ISSUE TITLE
Umstieg von A.L.F.R.E.D zu respondd / announced 

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#142]
Die Verwendung von gretap Tunneln auf den Gateways hat dazu gefuehrt, dass der alfred service nichtmehr startet. Die Grund ist tiefgruendig und eine Reparatur des service den Aufwand nicht wert.

Alternative: Umstieg auf redpondd / announced

Das loest das Problem auf den Gateways (und zukuenftig ggf. Servern), ist ein schickerer Weg zu tun, was alfred bisher tut, und geht konform mit dem Update des meshviewer zu hopglass.

**Comment by reissmann** [comment]
Would fix #115

**Comment by Noodlesalat** [comment]
Man sollte sich dahingehend folgenden Forumsbeitrag ansehen:
[https://forum.freifunk.net/t/announced-statt-alfred-im-mesh-nutzen-und-der-nachste-schritt/8654](https://forum.freifunk.net/t/announced-statt-alfred-im-mesh-nutzen-und-der-nachste-schritt/8654)

**Comment by Moorviper** [comment]
hm das war mal eine Zwischenlösung zwischen respondd und Alfred
Dürfte soweit mir bekannt nicht mehr weiterentwickelt worden sein.
da ja respondd in gluon ist

announced war meine ich nur zwischen 2015-2016.1.x in Gluon

frohes neues btw

respondd/announced wurde ja schon seit Anfang 2016 in der fffd firmware unterstützt und wird ja auch auf der Map mit hopglass verwendet

**Comment by mortzel** [comment]
Ist bereits umgestellt.
