### ISSUE TITLE
Rework backend infrastructure

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#143]
A whole bunch of things need to be reconsidered regarding the backend infrastructure.
More info: https://wiki.maglab.space/wiki/Freifunk_Fulda/Netz/Neu

**Comment by reissmann** [comment]
Might fix #109

**Comment by reissmann** [comment]
Addresses #92 and #3

**Comment by mortzel** [comment]
Planung liegt unter: https://pad.freifunk.net/p/fffd-netz
Vagrant für eine Testumgebung liegt unter: https://git.maglab.space/fffd/vagrant
Für salt gibt es einen rebuild branch: https://github.com/freifunk-fulda/saltstack-config/tree/rebuild

**Comment by mortzel** [comment]
- [x] Networknamespaces
- [x] Fastd
- [x] Batman
- [x] Gretab Tunnel zwischen Gateways
- [x] Wireguard zwischen Gateways und Servern
- [x] Bird 2.0
- [x] radvd
- [x] DHCP Subnetting
- [x] FFRL Uplink

**Comment by Noodlesalat** [comment]
Done. Thx @mortzel and @fooker ! :)
