### ISSUE TITLE
Switch to 801.11s

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#144]
Meshing over IEEE 801.11s seems to perform better than ad-hoc networks.

The switching can be done by using both methods for a transition time.

**Comment by mortzel** [comment]
Does our supported hardware supports this ieee standard?

**Comment by fooker** [comment]
AFAIK all gluon-supported hardware does so.

**Comment by Jo-Jo0** [comment]
For some Hardware you have to specify it specially, see [https://github.com/freifunk-fulda/site-fffd/commit/d3fca6784d74b3c11e2ace6812ad72d3e116cbec](url)

**Comment by mortzel** [comment]
We can not change from ibss to 801.11s without breaking mesh connections. So we need a step between only ibss and only 801.11s were we us ibss and 801.11s at the same time.

**Comment by Jo-Jo0** [comment]
Some devices (like archer c7) don't support ibss and 801.11s meshing at the same time. So we can only use both on devices that support it. See "Make variables" in the gluon 2016.2.1 documentation: https://gluon.readthedocs.io/en/v2016.2.1/user/getting_started.html#building-the-images

**Comment by Jo-Jo0** [comment]
started working on this in issue/144 branch

**Comment by fooker** [comment]
Done
