### ISSUE TITLE
Use Software to help users find the Firmware for their devices

### ISSUE THREAD

**Issue by Jo-Jo0** [freifunk-fulda/orga#145]
Use the Software that can be seen here: https://firmware.darmstadt.freifunk.net/
Git: https://github.com/freifunk-darmstadt/gluon-firmware-wizard

**Comment by Moorviper** [comment]
gäbe da auch noch:
https://github.com/ffwtbg/firmware-downloader

oder 
https://github.com/Freifunk-Hennef/ffhef-fw-dl
http://images.freifunk-hennef.de/downloader/firmware.php?id=0

**Comment by Noodlesalat** [comment]
Preview: [https://firmware.fulda.freifunk.net/selector/](https://firmware.fulda.freifunk.net/selector/)
Vielen Dank an @fooker

**Comment by fooker** [comment]
Alle links angepasst soweit gefunden. 
https://firmware.fulda.freifunk.net/selector/ sollte jetzt der default link zur fimware sein.
