### ISSUE TITLE
Setup mode does not show key but talks about it

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#146]
After hitting the 'Save & Reboot' button, the setup mode says

> This is your node's public key. It's used to connect the Freifunk-network. You don't have to save this key, it's automaticly uploaded to our gateway servers first time your node is connecting to Freifunk Fulda.

But no key is shown.

**Comment by fooker** [comment]
I think we should remove the message completely

**Comment by Jo-Jo0** [comment]
Should be fixed with https://git.maglab.space/fffd/site-fffd/commit/61d0c709afca7daa89739a8fc8f09f4d4d31327a
