### ISSUE TITLE
Shut ticketsystem down

### ISSUE THREAD

**Issue by Jo-Jo0** [freifunk-fulda/orga#147]
We should shut support.fulda.freifunk.net down and use Mail instead.

**Comment by Jo-Jo0** [comment]
removed the ticket system links from fulda.freifunk.net

**Comment by Moorviper** [comment]
<img width="1056" alt="bildschirmfoto 2017-05-22 um 16 00 55" src="https://cloud.githubusercontent.com/assets/3305254/26312461/edf13804-3f07-11e7-995e-ac787ac3a41e.png">
Joah, grammatikalisch ist es Deutsch :D 

Shutdown the ticket system.

**Comment by Jo-Jo0** [comment]
@Moorviper Danke für die Korrektur, dann bleiben wir am besten auch gleich im Deutschen ;)

**Comment by Jo-Jo0** [comment]
done
