### ISSUE TITLE
support tp-link WA901ND v5

### ISSUE THREAD

**Issue by Jo-Jo0** [freifunk-fulda/orga#153]
Der Support dieses Gerätes wurde per Mail angefragt. Im zugehörigen Firmwarebranch wird daran gearbeitet

**Comment by Jo-Jo0** [comment]
In Zukunft muss dafür gesorgt werden, dass Knoten, welche diesen branch nutzen auf stable migriert werden, sobald möglich

**Comment by Jo-Jo0** [comment]
Der build läuft, muss dann getestet werden.

**Comment by fooker** [comment]
All this devices are deprecated an will die soon. See https://fulda.freifunk.net/ende-des-supports-fuer-bestimmte-geraete/
