### ISSUE TITLE
support tp-link archer c7 v4

### ISSUE THREAD

**Issue by Jo-Jo0** [freifunk-fulda/orga#154]
I'm in need of firmware for this modell. 
@blockttron has build a patch, i will try to use this.

https://github.com/blocktrron/gluon/commit/7dae7d6e2c4e691ca3933ace27fadf91489fc3c3

**Comment by mweinelt** [comment]
merged into master branch on january 3rd

https://github.com/freifunk-gluon/gluon/commit/9273e56c63805cf38ec81328a4ea01d54011c052

**Comment by Jo-Jo0** [comment]
@mweinelt Thanks, I've seen this yesterday. Need to commit into our builds

**Comment by Noodlesalat** [comment]
Already done. Images can be found here: [https://firmware.fulda.freifunk.net/others/issue-154/6-390/factory/gluon-fffd-6-390-tp-link-archer-c7-v4.bin](https://firmware.fulda.freifunk.net/others/issue-154/6-390/factory/gluon-fffd-6-390-tp-link-archer-c7-v4.bin).
