### ISSUE TITLE
Support for TP-Link CPE 210/510 v2.0

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#158]

**Comment by fooker** [comment]
https://github.com/FreifunkVogtland/gluon/commit/ffa5a6526f319a43fbe9d0c7721e3c7b87d43dac.patch

**Comment by fooker** [comment]
The patch seems to work fine. Start to do some long-running tests.

**Comment by mortzel** [comment]
The support for the hardware is added in the openwrt master branch [1] and will be in some time in an openwrt release and then in a gluon release

[1] https://github.com/openwrt/openwrt/pull/937

**Comment by mortzel** [comment]
The support is merged into gluon master branch [1]

[1] https://github.com/freifunk-gluon/gluon/pull/1445

**Comment by Noodlesalat** [comment]
Device gets support with Gluon 2018.1
Build is already running so we can close this issue at this point.
See #164.
