### ISSUE TITLE
Build firmware with older gluon version for loadissue affected devices

### ISSUE THREAD

**Issue by Noodlesalat** [freifunk-fulda/orga#159]
Some devices are nearly unusable with the newest Gluon version because their CPU load increased massively. The bug appeared with the update to Gluon v2017.1.X. For more information see https://github.com/freifunk-gluon/gluon/issues/1243.

We plan to build firmware images based on a older gluon version (v2016.2.1) to support these devices until the bug is fixed in gluon itself. We cannot update them via the autoupdater because Gluon does not support a downgrade. So a manual flash is necessary.

List of all affected devices in the network of Freifunk Fulda:
---
**TP-Link TL-WR841N/ND v8**
- [ ] 5t3ff3n-Freifunk-Fulda - https://meshviewer.fulda.freifunk.net/#!v:m;n:a0f3c1057328

**TP-Link TL-WR841N/ND v9**
- [X] fffd-Lutherplatz - https://meshviewer.fulda.freifunk.net/#!v:m;n:c46e1f2d6836
- [ ] Gneisenau - https://meshviewer.fulda.freifunk.net/#!v:m;n:c46e1f3164ba
- [X] fffd-edelzell-02-rauschert - https://meshviewer.fulda.freifunk.net/#!v:m;n:14cc20b740f0
- [ ] Großentaft - https://meshviewer.fulda.freifunk.net/#!v:m;n:e894f651aef6

**TP-Link TL-WR841N/ND v10**
- [X] fffd-Juwelier-Bott - https://meshviewer.fulda.freifunk.net/#!v:m;n:60e327e7817a
- [X] fffd-Horas - https://meshviewer.fulda.freifunk.net/#!v:m;n:60e327edeef6

**TP-Link TL-WR841N/ND v11**
- [X] fffd-lauterbach-am-kirchhof-5 - https://meshviewer.fulda.freifunk.net/#!v:m;n:18a6f7ea5ee4
- [ ] fffd-opsa1 - https://meshviewer.fulda.freifunk.net/#!v:m;n:98ded0e54e08
- [X] fffdec086b837bb8 - https://meshviewer.fulda.freifunk.net/#!v:m;n:ec086b837bb8

**TP-Link TL-WA901N/ND v3**
- [ ] ReifenBrod - https://meshviewer.fulda.freifunk.net/#!v:m;n:c4e98479e594

**Ubiquiti NanoStation loco M2**
- [X] Lavanda-01 - https://meshviewer.fulda.freifunk.net/#!v:m;n:24a43c66a764

**Ubiquiti Bullet M2**
- [X] maglab_bullet01 - https://meshviewer.fulda.freifunk.net/#!v:m;n:6872514ae045

**Ubiquiti PicoStation M2**
- [X] fffd-kuenzell-07 - https://meshviewer.fulda.freifunk.net/#!v:m;n:6872516a2434

---
(Checkbox means: The owner shares contact information)

**Comment by fooker** [comment]
All this devices are deprecated an will die soon. See https://fulda.freifunk.net/ende-des-supports-fuer-bestimmte-geraete/
