### ISSUE TITLE
Knotenkarte

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#16]
Es fehlen ne Menge Daten - A.L.F.R.E.D verstehen und ffmap fixen (vgl. Knotenkarte Hamburg)

**Comment by SISheogorath** [comment]
still exists?

**Comment by SISheogorath** [comment]
Welche Erweiterungen sollen denn am Meshviewer und dem Map-Backend vorgenommen werden? (am besten mit einem Link zu einer Community, die es bereits hat, wenn es das denn schon gibt)

Genannt wurde ja bereits eine per Node-Graph bzw. Traffic und/oder Nutzerzahlen. Gibt es da weitere Punkte? 

@indigo bekommen wir die Statistiken aus dem Monitoring raus was ihr schon aufgebaut habt oder müssen wir die nochmal getrennt generieren?

**Comment by fooker** [comment]
Es gibt eine API im OpenNMS, über die man an die Daten kommt. Das bedeutet aber eigenen Code zum abfragen und proxien der Daten.

**Comment by SISheogorath** [comment]
Ich dachte eher was in Richtung: cronjob der die graphen generiert und dann auf den Webserver schiebt mit z.B. knotenid als Dateinamen. das würde die Einbettung sehr einfach gestalten

**Comment by reissmann** [comment]
Vielleicht waere ein Anfang ja mal ein Upgrade auf Version 4 der Knotenkarte?

Und statt das Rad immer wieder neu zu erfinden, koennte man sich ja mal die Branches dev und influxdb des ffmap-backend anschauen ...

**Comment by mortzel** [comment]
ffmap-backend wurde auf den aktuellen Master Branch von ffnord [1] upgedated.
Meshviewer wurde auf den aktuelle Master Branch von Moorviper [2] upgedated.

[1] https://github.com/ffnord/ffmap-backend/tree/c33ebf62f013e18bf71b5a38bd058847340db6b7
[2] https://github.com/Moorviper/meshviewer/tree/527b3d95bff517f93140b923fda38f0cda560e7f
