### ISSUE TITLE
Disable automated key upload

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#160]
We need more contact to node runners to discuss and plan things.

The following steps are needed:
- [x] Remove key-uploader from firmware
- [x] Add new page to configmode generating mail using `mailto:`
- [x] Disable key-uploade servers
- [x] Synchronize `fastd-peers` repository to all gateways
- [x] Install and run keymaster bot

**Comment by fooker** [comment]
Keymaster: https://git.maglab.space/fffd/keymaster
Peers: https://git.maglab.space/fffd/fastd-peers

Later is private by intention as it contains Mail-Adresses

**Comment by Noodlesalat** [comment]
depends on #166

**Comment by Noodlesalat** [comment]
Also we have to remove and disable the old fastd config for the autokey package.

**Comment by fooker** [comment]
The keymaster bot is deployed on srv1 and ready for testing.

**Comment by mortzel** [comment]
Firmware 736 in branch issue/166 will have full support

**Comment by Noodlesalat** [comment]
The keyupload package has been already removed with firmware version 7. All keys are now saved in a Git repository. Old keys are marked with the "old-" prefix.
