### ISSUE TITLE
Add support for new backbone networks

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/orga#166]
In the process of the rework of the backend infrastructure  #143 and to add support for batman domains the ip networks have changed. So the firmware has to be configured to support the new networks.

**Comment by mortzel** [comment]
Firmware 736 will have the full support for the new infrastructure with:
* replaced keyupload with mail
* changed fastd ports
* extended prefixes
* added ips for gw01 and gw02

**Comment by Noodlesalat** [comment]
We switched to the new netns-backbone with firmware v8. Thx @mortzel and @fooker for their work! :)
