### ISSUE TITLE
Split network into different domains (multidomain)

### ISSUE THREAD

**Issue by Noodlesalat** [freifunk-fulda/orga#167]
Gluon 2018.1 brings multidomain support. [1] [2]
The idea is that you split your big network with a high level of management traffic into many little domains in order to reduce management traffic in these litte domains. With firmware v7 we should integrate the multidomain support into our network in order to be prepared for the future.

[1] [https://github.com/freifunk-gluon/gluon/blob/master/docs/releases/v2018.1.rst#multidomain-support](https://github.com/freifunk-gluon/gluon/blob/master/docs/releases/v2018.1.rst#multidomain-support)
[2] [https://github.com/freifunk-gluon/gluon/blob/master/docs/features/multidomain.rst](https://github.com/freifunk-gluon/gluon/blob/master/docs/features/multidomain.rst)

**Comment by Noodlesalat** [comment]
This depends on #143, #164, #166

**Comment by Noodlesalat** [comment]
Currently working in issue/168 (#168)
https://git.maglab.space/fffd/site-fffd/pipelines/453

**Comment by mortzel** [comment]
Firmware with Multidomains Support in #181 
Fix for nextnode dns in #182

**Comment by mortzel** [comment]
Domains configured on the gateways:
- dom0 -> Legacy (hidden)
- dom1 -> Landkreis Fulda
- dom2 -> Vogelsbergkreis
- dom3 -> Landkreis Hersfeld-Rotenburg
- dom4 -> Schwalm-Eder-Kreis
- dom5 -> Main-Kinzig-Kreis
- dom6 -> Wartburgkreis
- dom7
- dom8
- dom9
- dom10
- dom11
- dom12 -> Events (hidden)
- dom13 -> Stadt Alsfeld (hidden)
- dom14 -> Other (all nodes which do not fit in on of the other domains)

**Comment by Noodlesalat** [comment]
Fixed since [https://git.maglab.space/fffd/site-fffd/commit/47859a4f327b736bb744f8f40b7d1555175ef29c](https://git.maglab.space/fffd/site-fffd/commit/47859a4f327b736bb744f8f40b7d1555175ef29c)
Documented in [https://git.maglab.space/fffd/saltstack/blob/master/pillar/common/domains.sls](https://git.maglab.space/fffd/saltstack/blob/master/pillar/common/domains.sls)
