### ISSUE TITLE
Add support for DFS on outdoor devies

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/orga#168]

**Comment by mortzel** [comment]
Scheint zu laufen:

root@maglabacmesh:~# logread | grep DFS
Wed Apr 18 16:13:12 2018 daemon.notice hostapd: client0: DFS-RADAR-DETECTED freq=5560 ht_enabled=1 chan_offset=0 chan_width=1 cf1=5560 cf2=0
Wed Apr 18 16:13:12 2018 daemon.notice hostapd: client0: DFS-NEW-CHANNEL freq=5660 chan=132 sec_chan=0
Wed Apr 18 16:13:12 2018 daemon.warn hostapd: DFS failed to schedule CSA (-22) - trying fallback
Wed Apr 18 16:13:12 2018 kern.debug kernel: [542816.144126] ath: phy0: DFS: radar found on freq=5560: id=4, pri=242, count=10, count_false=0
Wed Apr 18 16:13:12 2018 kern.debug kernel: [542816.152418] ath: phy0: DFS: radar found on freq=5560: id=4, pri=245, count=10, count_false=0
Wed Apr 18 16:13:12 2018 kern.debug kernel: [542816.152480] ath: phy0: DFS: radar found on freq=5560: id=4, pri=245, count=10, count_false=0
Wed Apr 18 16:13:14 2018 daemon.notice hostapd: client0: interface state COUNTRY_UPDATE->DFS
Wed Apr 18 16:13:14 2018 daemon.notice hostapd: client0: DFS-CAC-START freq=5660 chan=132 sec_chan=0, width=0, seg0=132, seg1=0, cac_time=60s
Wed Apr 18 16:13:14 2018 daemon.notice hostapd: client0: DFS-RADAR-DETECTED freq=5560 ht_enabled=1 chan_offset=0 chan_width=1 cf1=5560 cf2=0
Wed Apr 18 16:14:18 2018 daemon.notice hostapd: client0: DFS-CAC-COMPLETED success=1 freq=5660 ht_enabled=1 chan_offset=0 chan_width=1 cf1=5660 cf2=0
Wed Apr 18 16:14:18 2018 daemon.notice hostapd: client0: interface state DFS->ENABLED
Wed Apr 18 16:43:14 2018 daemon.notice hostapd: client0: DFS-NOP-FINISHED freq=5560 ht_enabled=0 chan_offset=0 chan_width=0 cf1=5560 cf2=0

**Comment by mortzel** [comment]
@Noodlesalat Maybe broken ?

**Comment by Noodlesalat** [comment]
It seems like the outdoor mode settings are not applied after first config wizard.

**Comment by mortzel** [comment]
Doesn't work correctly at the moment.

If you flash a CPE510 fresh with the v7 everythings looks fine, if you update from v6 to v7 the outdoor mode is enabled int '/etc/config/gluon' but the wireless config is still the old config. If you flash a wr3600, for which the outdoor mode is not enabled by default, and enable the outdoor mode the config is in '/etc/config/gluon' but the wireless config is not changed, so like if we update a cpe510 from v6 to v7.

**Comment by Noodlesalat** [comment]
This package needs additional testing. Reopened.
The newest firmware build should fix two bugs:
- disabled mesh wifis got activated while upgrading the firmware
- the outdoor mode was not enabled after first configuration because the 200-wireless executabled was not executed

**Comment by Noodlesalat** [comment]
Fixed for now, but needs additional work.

**Comment by Noodlesalat** [comment]
A new version has been published. We should build firmware to test this version.

**Comment by Noodlesalat** [comment]
Testing currently takes place in Darmstadt. We can close this over here, a tested version of the outdoor-mode is going to arrive in our development branch after testing has finished.
