### ISSUE TITLE
Nodes mit Label versehen

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#17]
Jede Node sollte ein Label haben können.

Dieses Label soll einen Namen der betreibenden Institution enthalten und daher keinen Einschränkungen unterliegen. Das Label soll auch auf der Karte angezeigt werden.

**Comment by mfuhrmann** [comment]
Geht es hierbei um die Metadaten im Meshviewer? Wenn ja, sollte auch ein Feld für die URL zu deren Webseite mit rein. Gewerbetreibende lieben Backlinks.

**Comment by fooker** [comment]
Nobody asks for this in the last 3 years...
