### ISSUE TITLE
Incresse MTU to 1312

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/orga#171]
https://gluon.readthedocs.io/en/v2018.1.x/user/faq.html#what-is-a-good-mtu-on-the-mesh-vpn

**Comment by Noodlesalat** [comment]
Going to be fixed later.

**Comment by mortzel** [comment]
We will deploy dom1-14 with an MTU of 1312 and run dom0 -> legacy with the old MTU of 1280

**Comment by Noodlesalat** [comment]
Fixed since [https://git.maglab.space/fffd/site-fffd/commit/47859a4f327b736bb744f8f40b7d1555175ef29c](https://git.maglab.space/fffd/site-fffd/commit/47859a4f327b736bb744f8f40b7d1555175ef29c)
