### ISSUE TITLE
Das Model mit in den mailto-key-text aufnehemen

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#174]
Das Modell sollte da mit rein.

**Comment by Noodlesalat** [comment]
Started working on this. Waiting for build job to finish in order to test the changes.

**Comment by Noodlesalat** [comment]
Works!
```
{{
fffd5254000faf1c
x86-64
52:54:00:0f:af:1c
97fee17b45fe96dccccb50fe7ce30d8a3a4e369b66a2e4fd7e71867c6261baaf
}}
```

**Comment by Noodlesalat** [comment]
This is not finished yet. We have to adjust the keybot for automatic key-submission in order to recognize the model.

**Comment by mortzel** [comment]
@fooker has fixed the keybot in the branch development branch https://git.maglab.space/fffd/keybot/tree/development and this is running on srv01
