### ISSUE TITLE
migrate autoupdater path

### ISSUE THREAD

**Issue by Noodlesalat** [freifunk-fulda/orga#175]
I would like to have the firmware selector available directly under firmware.fulda.freifunk.net.

We have to fulfill these steps:
- [ ] update path in all firmware versions
- [ ] update selector paths

**Comment by mortzel** [comment]
firmware.fulda.freifunk.net points to the Selector
firmware.services.fffd.eu points to the image folders

So we do not need to change anything in the firmware
