### ISSUE TITLE
Prepare for next firmware release

### ISSUE THREAD

**Issue by Noodlesalat** [freifunk-fulda/orga#179]
We mixed up the different branches for the next firmware release like pros. It's time to clean that up. This branch is based on https://github.com/blocktrron/gluon/tree/ffda-1.6.1. It contains Gluon 2018.2.X, the outdoor mode and the corresponding fixes.
In this branch we compare:
#167, #168, #174, #175, #176

**Comment by mortzel** [comment]
#167 done with #181 #182 
#168 done with #181 
#174 done in #181 and fixed on server by @fooker 
#175 done on the webserver
#176 done with #181
