### ISSUE TITLE
Doku: Rechner schuetzen

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#18]
Dokumentation erstellen, die den Nutzern erklaert, wie sie ihren eigenen Rechner im Freifunk-Netz schuetzen, wie der Betrieb eines Freifunk-Routers sich auf das Heimnetz auswirkt und wie es grundsaetzlich mit der Sicherheit aussieht (unverschluesseltes WLAN, alle Clients sehen sich gegenseitig, usw.)

**Comment by SISheogorath** [comment]
Gibt es sowas in der Richtung schon von anderen Freifunknetzen? ggf. müsste man es nur anpassen. Außerdem lässt sich leider schwer universell beschreiben, die die Firewall ideal konfiguriert ist, schließlich kommt das auf die use-cases an.

Außerdem sollte man sich fragen, für "welche Sorte User" man die Doku schreiben möchte, denn das Pflegen von - sagen wir mal grundsätzlich - 3 (Windows, MacOS, Linux) Dokus bringt eine Menge Arbeit mit sich. Zumal leider das Interesse daran im Verhältnis zum Aufwand recht gering ist.

Ich würde eher eine Verlinkung auf diverse Seiten vorschlagen, die sich mit dem Thema Sicherheit in offenen WLANs beschäftigt oder eben im Freifunk-Wiki einen oder mehrere Eintrag/Einträge verfassen.

**Comment by reissmann** [comment]
Wird dieses Issue noch bearbeitet?

Hier mein Vorschlag: https://fulda.freifunk.net/sicher-unterwegs-im-unverschluesselten-freifunknetz/

**Comment by andichrist-fffd** [comment]
Soll ich den Artikel mal über Facebook raus hauen? Über die normale
Navigation auf der Webseite finde ich das gerade nicht? Hat das nen
Grund? Sollte das vielleicht zu den Anleitungen?

Am 01.12.2015 um 17:52 schrieb Sven Reissmann:

**Comment by mfuhrmann** [comment]
@reissmann Ich habe die Sidebar auf der Homepage ein wenig angepasst. Man kann das Dokument dort gut finden. Auch die anderen Anleitungen & FAQ. Wenn es mal mehr Anleitungen werden, sollte man es sicherlich anders lösen. Ich schließe das Ticket daher erstmal.
