### ISSUE TITLE
Use freifunk router as dns server

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/orga#182]
To support the dns resolution for nextnode.fffd.eu in an multidomain setup we should configure the router as the dns server and forward the dns querys of the router to our anycast dns servers.

**Comment by mortzel** [comment]
```
dns = {
		cacheentries = 0,
		servers = { 'fd00:65a8:93a4:f::1' },
	},
```

**Comment by Noodlesalat** [comment]
Fixed since [https://git.maglab.space/fffd/site-fffd/commit/47859a4f327b736bb744f8f40b7d1555175ef29c](https://git.maglab.space/fffd/site-fffd/commit/47859a4f327b736bb744f8f40b7d1555175ef29c)
