### ISSUE TITLE
Change IP of gw02

### ISSUE THREAD

**Issue by Noodlesalat** [freifunk-fulda/orga#187]
gw02 has been moved to a new hoster and got a new ip address

**Comment by mortzel** [comment]
GW02:
- 89.163.247.235
- 2001:4ba0:fff5:120:1001::fffd

GW04:
- Die IP wird sich hier vermutlich auch demnächst ändern, da der alte Server von GW04 gekündigt wurde

**Comment by Noodlesalat** [comment]
Done.
https://git.maglab.space/fffd/site-fffd/commit/5f5bf6ef7c29458ece8ae974605d6e0459e6020a

We will open a new issue for gw04.
