### ISSUE TITLE
own tiles cache for setup mode selection

### ISSUE THREAD

**Issue by Noodlesalat** [freifunk-fulda/orga#188]
The builtin tiles cache from OSM is very slow. We should setup our own.

**Comment by mortzel** [comment]
We already have a tilescache server.
https://git.maglab.space/fffd/saltstack/blob/master/pillar/hosts/tilescache/private/tilescache.sls
https://git.maglab.space/fffd/saltstack/blob/master/state/meshviewer/tiles.sls
