### ISSUE TITLE
Firmware-Support für Mikrotik RouterOS MetaROUTER

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#19]
Die Firmware sollte auch als MetaROUTER auf Mikrotik RouterOS laufen.

**Comment by SISheogorath** [comment]
Wenn ich das richtig sehe, müssen wir dazu nur als Target auch x86-generic bauen. Sollte mit der neuen Firmware kein Problem sein mehr sein. Muss allerdings in die Buildumgebung eingebaut und getestet werden.

**Comment by SISheogorath** [comment]
Okay, es ist doch nicht so einfach wie gedacht. Wir müssten im Build prozess für dieses eine Image einen patch in OpenWrt unter bringen und es stellen sich dennoch die Fragen: Wer wird es nutzen und sind die, die es nutzen nicht auch selbst in der Lage die Firmware mit entsprechenden Patches zu bauen?

In `#gluon` meinte DO9XE, dass er es bisher noch nicht zurecht geschnitten bekommen hat und stattdessen scheinbar irgendeinen Router mit im RACK verbaut hat. ggf. wäre das wohl mit eine der Lösungen. Wenn man da aber basteln, will, wäre er interessiert daran mit zu wirken

**Comment by Jo-Jo0** [comment]
müsste mit gluon 2017 möglich sein, da kommen eh einige Targets neu dazu

**Comment by Jo-Jo0** [comment]
"ar71xx-mikrotik" is in our current build.sh, sadly this does not create any images for the devices.
