### ISSUE TITLE
Überarbeiten der NextNode Adressen

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#2]
Jede Node ist über die NextNode-Addresse erreichbar. Im moment sehen diese aber etwas unstrukturiert aus:
- fd00:fffd:fffd::255
- 10.185.0.255

DNS-Records sollten dafür auch angelegt werden.

**Comment by reissmann** [comment]
Das ist im Falle von IPv4 die letzte Adresse im Bereich fuer Dienste/Infrastruktur. 
Im Falle von IPv6 ist es ebenfalls die 255 um es nicht unnoetig kompliziert zu machen.

DNS Records (A und AAAA) sind erstellt. 
Die Next-Node Adresse ist erreichbar unter: nextnode.fffd
