### ISSUE TITLE
Repository für fehlende Pakete erstellen

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#20]
Einige Software ist nicht in den Debian-Repositories enthalten. Für diese Software sollte ein eigenesRepository erstellt werden. So können die Server auch mit Updates versorgt werden.

Folgende Pakete sollten verfügbar sein:
- fastd
- libuecc
- batman-adv
- batctl
- alfred
- alfred-json

**Comment by fooker** [comment]
Only batctl (and bird2) is build from source right now. Everything else is coming from repos.

**Comment by fooker** [comment]
batctl maybe can be replaced by iproute2 (but what about status output like `batctl gwl`?)

**Comment by mortzel** [comment]
Akutell bauen wir noch folgende Pakete von Source auf den Gateways mit Saltstack:
- bird2
- batctl

Zusätzlich wird in dem Docker Build Container noch libuecc von Source gebaut

**Comment by Noodlesalat** [comment]
Fixed in saltstack states
