### ISSUE TITLE
Fehlerhafte Nodes triggern staendig fastd reload

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#21]
Es scheint zwei Nodes zu geben, die staendig ihren fastd-Key neu hochladen und dadurch fastd reload triggern.

**Comment by reissmann** [comment]
Das sind die beiden Knoten:
    fffd-greb-wenneschneiderges
    fffd-Centhof

Beide verwenden stable-2-20150409
Beide sind TP-Link TL-WR841N

**Comment by fooker** [comment]
Eine Lösung könnte sein, das Upload-Script so zu ändern, dass nur wenn eine neue MAC-Adresse hinzugekommen ist ein reload durchgeführt wird.

**Comment by reissmann** [comment]
Upload script geaendert.
