### ISSUE TITLE
VPN via mullvad is really slow

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#22]
Speed is varying between 3 and 20 MBit/s. We might need a better solution.

**Comment by reissmann** [comment]
Eventuell lohnt ein Umstieg auf Perfect Privacy: https://www.perfect-privacy.com
Preislich natuerlich eine andere Liga.

**Comment by SISheogorath** [comment]
Ist das noch aktuell? Ansonsten -> Closed

**Comment by mortzel** [comment]
Aktuell wird mullvad noch als VPN-Anbieter verwendet. Allerdings laeuft unser Account in 10 Tagen, also am 31.07.15 aus.
Kurz zuvor sollte ein Umstieg auf Perfect Privacy geschehen.

**Comment by SISheogorath** [comment]
Wie sieht es inzwischen eigentlich mit der VPN Umstellung aus? Hat das auf GW01 jetzt geklappt?

**Comment by reissmann** [comment]
Auf gw02 wird seit dem Wochenende perfect-privacy verwendet.

**Comment by reissmann** [comment]
Ok, gw01 auch erledigt.
- VPN umgestellt (config in /etc/openvpn/perfectprivacy.conf)
- Interface umbenannt in fffd.internet
- Interface zu vnstat db hinzugefuegt
- POSTROUTING angepasst
- Skripte in fffd-check-gateway angepasst
- SNMP config angepasst
- OpenNMS poller "UplinkVPN_Connectivity" updated
