### ISSUE TITLE
Ueberarbeitung der Texte im Konfigurationsmodus-UI

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#25]
Die Texte sollten etwas aussagekraeftiger sein. Da steht z.B.:

```
msg_pubkey = [[
  Dies ist der öffentliche Schlüssel deines Freifunkknotens.
]],
```

Vielleicht koennte man noch einen Satz dazu schreiben, was das jetzt bedeutet ...

**Comment by SISheogorath** [comment]
Done in https://github.com/freifunk-fulda/site-fffd/pull/7

**Comment by fooker** [comment]
Einige Texte sind immer noch sehr unaussagekräftig. Ich würde gerne ein Review mit einem unerfahrenen Nutzer machem.

Das können wir aber im nächsten Release machen.

**Comment by fooker** [comment]
Sieht gut aus soweit.
