### ISSUE TITLE
Neue fastd-Schluessel fuer Gateways

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#26]
Die drei bisher verfuegbaren (in der site.conf angegebenen) fastd-Schluessel sind in Verwendung. Um nicht durch die Bereitstellung eines neuen Gateway auch ein Firmwareupdate erstellen zu muessen, sollten 1-2 weitere Schluessel vorgeneriert und bei Gelegenheit in die Config hinzugefuegt werden.

**Comment by fooker** [comment]
Added 3 new keys to development image.
