### ISSUE TITLE
Switch websites to fulda.freifunk.net

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#29]
- Migrate all services to fulda.freifunk.net
- Add redirects from freifunk-fulda.de to fulda.freifunk.net
- Get ssl certificates for fulda.freifunk.net and its subdomains

**Comment by reissmann** [comment]
Zertifikate sind beantragt

**Comment by reissmann** [comment]
Done. Stupid Wordpress is broken.

**Comment by SISheogorath** [comment]
Some URL are still on old style. Example: http://nodegame.freifunk-fulda.de/

**Comment by SISheogorath** [comment]
My fault. Wordpress does automatic rewrite but nodegame not. nodegame is accessable by both.
nodegame.fulda.freifunk.net and nodegame.freifunk-fulda.de/
