### ISSUE TITLE
Einge IPv6-Address-Range für Nodes

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#3]
Die Nodes teilen sich momentan ein IPv6-Address-Range mit allem anderen. Zum generieren der Reverse-Zone für die Nodes ist es von vorteil, eine eigene Range zu definieren:

fd00:fffd:fffd::/48 als Netz
fd00:fffd:fffd:0:\* für Server
fd00:fffd:fffd:1:\* für Nodes
fd00:fffd:fffd:2:\* für Clients

**Comment by mortzel** [comment]
Depends on #6

**Comment by fooker** [comment]
The IPv6 ULA is configured by a single radvd instance. Therefore we can not distinguish the different type of nodes. Maybe we should use something like https://all-knowing-dns.zekjur.net/ instead.
