### ISSUE TITLE
Add request System for static IP

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#33]
How do we want the static IP request process to be? Not everybody has a github account ...

**Comment by mortzel** [comment]
Why not build a webinterface for _IP request_ on top of phpipam[1].

[1] http://phpipam.net/

**Comment by reissmann** [comment]
Go ahead, @mortzel

**Comment by SISheogorath** [comment]
may also depends on #3

**Comment by mortzel** [comment]
yea, we have to deal with request for IPv4 and IPv6

**Comment by SISheogorath** [comment]
Wurde vorerst durch eine eigene Kategorie im Ticketsystem gelöst. Wer eine stärkere Automatisierung möchte, kann diese gerne einbauen.

https://support.fulda.freifunk.net
