### ISSUE TITLE
Decrease MTU

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#35]
In order to support IPv6 connections with fastd, the MTU must be decreased, as the IPv6 header is 20 byte larger that the IPv4 header.

**Comment by reissmann** [comment]
In fastd >= 17, the MTU on both ends of the connection must be the same!

**Comment by reissmann** [comment]
Reduced to 1406 @ gw03 for testing

**Comment by fooker** [comment]
Firmware > 66 uses the new MTU

**Comment by fooker** [comment]
Fixed in latest development build and on gw03
