### ISSUE TITLE
Gateway default Website CSS broken

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#36]
In google chrome, the css of the gateways default website is broken

![broken](https://cloud.githubusercontent.com/assets/833161/8638223/5eac096e-28b4-11e5-8d08-f91d701f72aa.png)

**Comment by reissmann** [comment]
Also, scaling does not work well.

The corresponding project is freifunk-fulda/fffd-keyupload, which includes the directory website, holding the gateways default website.

Maybe the whole thing should be reworked ...

**Comment by SISheogorath** [comment]
How about simply create a rewrite to fulda.freifunk.net?
