### ISSUE TITLE
Update our metadata in IC-VPN repo

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#37]
The IC-VPN metadata repo holds information on the IP address ranges used by the communities. We neet to update this data after changing the IPv6 prefix and our domain name (to fulda.freifunk.net).

Depends on #31

**Comment by SISheogorath** [comment]
needs fulda2 and fulda3 to get closed? 

First steps are done with https://github.com/freifunk/icvpn/pull/103

**Comment by reissmann** [comment]
done
