### ISSUE TITLE
Change SSID to fulda.freifunk.net

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#38]
When and how do we do this? 
Should we offer both freifunk-fulda.de and fulda.freifunk.net for a while?
Are there any implications I am not aware of?
Any suggestions?

**Comment by SISheogorath** [comment]
further stuff: https://github.com/freifunk-fulda/site-fffd/pull/3

**Comment by fooker** [comment]
Fixes in latest development.

**Comment by fooker** [comment]
For explaination: the latest build will show the following SSIDs:
freifunk-fulda.de
fulda.freifunk.net
freifunk.net
