### ISSUE TITLE
Manifest-Datei existiert doppelt

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#4]
Soweit ich sehe, wird der Link von "${BRANCH}.manifest" auf "manifest" nicht mehr benoetigt. Dieser Build-Step kann einfach entfernt werden.

**Comment by reissmann** [comment]
Wenn wir issues in einem eigenen repo sammeln, dann sollten diese einen Hinweis enthalten, worauf sie sich beziehen. Um welches repo geht es hier?

**Comment by fooker** [comment]
Gar kein Repo. Jenkins macht das.

**Comment by fooker** [comment]
Das erstellen des Symlinks wurde entfernt, da der aktuelle autoupdater diesen nicht benötigt.
