### ISSUE TITLE
Peering im IC-VPN und dn42

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#40]
Auf dem WCW 2015 haben wir bereits angefangen, Peerings im IC-VPN [1][2] einzurichten. Das ganze sollte fertiggestellt werden. Ausserdem koennen peerings mit weiteren Communities (z.B. dn42 [3]) eingerichtet werden.

[1] https://wiki.freifunk.net/IC-VPN
[2] https://github.com/freifunk/icvpn-meta
[2] https://dn42.eu/

**Comment by SISheogorath** [comment]
:+1:

**Comment by SISheogorath** [comment]
Wie sieht denn der aktuelle Stand aus? 
Es hieß auf GW03 ist es soweit eingerichtet, aber das Routing ist noch schief. Ein Statement zum aktuellen Stand durch die Bastler wäre mal ganz schick. Ggf. sollte es am CCCamp 2015 gefixt werden.

**Comment by reissmann** [comment]
fixed.
