### ISSUE TITLE
Fix wordpress plugins

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#41]
There are some wordpress plugins that broke while switching to fulda.freifunk.net.
- The firmware plugin does not show anything anymore: https://fulda.freifunk.net/anleitungen/die-passende-freifunk-fulda-firmware-auswahlen/
- The Simple Lightbox plugin does not work anymore (click on any image)

Also most of the links (including image links) reference to freifunk-fulda.de (WTF?)

**Comment by reissmann** [comment]
Caused by #29

**Comment by mortzel** [comment]
Did you changed all entries in the database from freifunk-fulda.de to fulda.freifunk.net ?

**Comment by fooker** [comment]
The firmware plugin works after fixing the SSL chain.

**Comment by SISheogorath** [comment]
We removed all "Simple Lightbox" integrations (actually 1 picture) and change the reference to map viewer.

I'll close. If something is still wrong we can reopen.
