### ISSUE TITLE
FAQ erweitern - Thema Landingpages

### ISSUE THREAD

**Issue by mfuhrmann** [freifunk-fulda/orga#43]
Da ich scheinbar nicht der erste war, der diese Frage im IRC gestellt hat, sollte das FAQ um diesen Punkt erweitert werden.

Im IRC wurde folgendes dazu gesagt:

> ...und uns entschieden, dass wir keine wollen ... das ist gleube ich die verbreitete meinung bei den freifunk communities
> 1. es bricht z.b. vpn-gezeugse, weil man vpn erst ausmachen muss um die landingpage zu sehen
> 2. es fuehrt dazu, dass wir personenbezogene daten erheben muessen (mac adresse der nutzer, um die landing page nicht erneut anzuzeigen)

Im FAQ könnte so etwas stehen wie:

> Sind Landing Pages erlaubt bzw. technisch machbar?
> 
> Nein. Es gibt ein paar gravierende Gründe die dagegen sprechen. Zum einen müsste man die VPN Verbindungen wieder öffnen, um Landing Pages anzuzeigen. Außerdem müssten personenbezogene Daten wie die MAC Adresse der User gesammelt werden, um ggfs. Landing Pages nicht erneut anzeigen zu lassen.

**Comment by SISheogorath** [comment]
Relays to #14

**Comment by SISheogorath** [comment]
Eine Idee, wenn wir so oder so das Wiki überarbeiten, sollten wir einige Ausführlichere Beiträge so z.B. die Idee mit den Landingpages eher im Wiki vermerken, als im FAQ.
Insbesondere deshalb, weil solche FAQ einträge denke ich nur eine recht kleine Schnittmenge treffen. Stattdessen könnte ich mir etwas vorstellen wie 

```
Welche Vorteile hat Freifunk für mich als Unternehmen/Unternehmer?
```

und dann dort unter anderem einen Beitrag im Wiki verlinken wo unter anderem auf die Landingpage sowie Pagebranding etc. eingegangen wird und aufgezeigt wird, welche Alternativen wir dazu anbieten bzw. wie man eben etwas ähnliches nutzen kann.

**Comment by SISheogorath** [comment]
Wurde zum Wiki FAQ hinterlegt. https://wiki.mag.lab.sh/wiki/Freifunk_Fulda/Firmware_FAQ#Firmware_FAQ
