### ISSUE TITLE
Add firmware-build documentation

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#45]
Really, would be nice. Especially on how to update submodules, and so on.

**Comment by fooker** [comment]
Whats missing in https://wiki.mag.lab.sh/wiki/Freifunk_Fulda/Firmware ?

**Comment by reissmann** [comment]
- How to link gluon repo with site-config repo
- How to pin a specific version of site.conf
- How to sign the frmware?
  - Do we have a process for this? 
  - Where to pull the manifest, how to upload it again? 

-> Just help people to understand how to build firmware ...

**Comment by indigo423** [comment]
Added CI System documentation in https://wiki.mag.lab.sh/wiki/Freifunk_Fulda/Continuous_Integration

**Comment by fooker** [comment]
Documented in the [readme](https://git.maglab.space/fffd/site-fffd/blob/development/README.md). CI has moved to gitlab, too.
