### ISSUE TITLE
Neue TP-Link Geräte nötig?

### ISSUE THREAD

**Issue by mfuhrmann** [freifunk-fulda/orga#48]
Lt. Hersteller sind die TP Link Geräte 3600 und 4300 Auslaufmodelle: http://www.tp-link.de/products/discontinued/
Ggfs. sollten schon mal neue Geräte gesucht/getestet werden.

**Comment by mfuhrmann** [comment]
Der FF Rheinland hat einige neuere TP Link Geräte gelistet:
https://wiki.freifunk-rheinland.net/Firmware/Kompatibilit%C3%A4t

**TL-WR1043ND**
http://www.tp-link.de/products/details/?categoryid=238&model=TL-WR1043ND

**TL-WR941ND**
http://www.tp-link.de/products/details/?categoryid=238&model=TL-WR941ND

Vielleicht kann jemand unsere Firmware dafür anpassen/übernehmen?

**Comment by reissmann** [comment]
Wir unterstuetzen diese Modelle.
