### ISSUE TITLE
Falscher IPv4-Prefix für Nodes

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#5]
Der IPv4-Prefix ist laut site.conf
 10.185.0.0/18
Sollte das nicht /16 sein?

**Comment by reissmann** [comment]
Siehe https://wiki.mag.lab.sh/wiki/Freifunk_Fulda/Gateway#IPv4:_DHCP

**Comment by fooker** [comment]
Es geht mir um den Eintrag in der site.conf. Sollte der nicht das gesammte Netz umfassen?

**Comment by fooker** [comment]
"The IPv4 Subnet of your community mesh network in CIDR notation"

http://gluon.readthedocs.org/en/latest/user/site.html

**Comment by reissmann** [comment]
10.185.0.0/18 ist unser IPv4 Subnet. Mehr nutzen wir derzeit nicht. Der Rest ist reserved.
Ebenso ist fd00:fffd:fffd:0/64 unser genutztes IPv6 Subnet, obwohl uns ein /48 zugewiesen ist.

**Comment by fooker** [comment]
Verstehe.
