### ISSUE TITLE
FAQ/Wiki Beitrag hinzufügen: Wie schalte ich 5GHz ab?

### ISSUE THREAD

**Issue by mfuhrmann** [freifunk-fulda/orga#50]
Ich schreibe das jetzt in ein Issue, damit es schon mal irgendwo steht.
Quelle: https://forum.freifunk.net/t/5ghz-wlan-abschalten/4281
- über SSH aufschalten
- **uci show wireless** → dort Einträge zu _radio0_ und _radio1_ anschauen
- eines davon sollte die Eigenschaft _hwmode=11a_ haben; dies ist das 5GHz-Radio
- das entsprechende Radio (temporär) ausschalten mit **wifi down radioX** (X = 0 oder 1)
- bei Bedarf entweder:
  mit **wifi up radioX** wieder anwerfen, oder
  mit **uci set wireless.radioX.disabled=1** und **uci commit** permanent ausschalten (permanent im Sinne von überlebt reboot, nicht überlebt Firmwareupdates)

**Comment by SISheogorath** [comment]
Was würdest du denn davon halten, wenn du es direkt ins Wiki einträgst? Selbst wenn er sehr spartanisch ist, ist es einfacher, als über Github das Konzept nahe zu legen und dann eben dadurch doppelt Arbeit zu generieren. Einmal von dir, um das ganze in GitHub zu hacken und einmal für die Person, die es ins Wiki übertragt. Wiki-Accounts kosten nichts und sind schnell angelegt. Außerdem ist sowas auch schnell mal im Wiki eingetragen. Vielleicht nicht schön, aber aufgehübscht ist es dann doch schneller, wenn man nochmal alles selbst formulieren muss.

Einfach https://wiki.mag.lab.sh/ und go.

Ich würde vorschlagen hierfür eine Firmware FAQ Seite neu zu erstellen. (Andere Namen wären sehr willkommen) somit würde man auch kleinere Tätigkeiten nicht zu 2 Zeilern im Wiki zusammenschrumpft und die Kategorie Freifunk unnötig unübersichtlich wird.

**Comment by mfuhrmann** [comment]
Done: https://wiki.mag.lab.sh/wiki/Freifunk_Fulda/Firmware_FAQ

**Comment by SISheogorath** [comment]
:+1: Sieht ja wunderbar aus und ist ein guter Ansatzpunkt noch vieles mehr aufzunehmen. Ich mach mich diese Woche mal dran ein bisschen auf zu hübschen, aber es steht schonmal drin. :)
