### ISSUE TITLE
Wiki/FAQ Artikel SSH Zugriff

### ISSUE THREAD

**Issue by mfuhrmann** [freifunk-fulda/orga#51]
Ggfs. sollte man noch mal ein FAQ/Wiki machen, dass erklärt, wie man sich über SSH aufschaltet. Das hier ist so hilfreich nicht: https://fulda.freifunk.net/anleitungen/zugriff-auf-einen-freifunk-knoten/

Der Text ist so in Ordnung. Aber es fehlt:
- Wie komme ich wieder in diesen Expert Mode?
  Ich selbst habe es nur über Reset Taste am Gerät und dann über die 192.168.0.1 wieder bekommen. Gibt es noch einen anderen Weg?
- ggfs. noch ein Bsp. von dem ssh login: ssh root@10.185.0.1 

Wenn das hier existiert könnte man den ersten Punkt von hier https://github.com/freifunk-fulda/orga/issues/50 damit verlinken.

**Comment by reissmann** [comment]
Wie komme ich wieder in diesen Expert Mode? Ich selbst habe es nur über Reset Taste am Gerät und dann über die 192.168.0.1 wieder bekommen. Gibt es noch einen anderen Weg?

-> Nein. Siehe: https://fulda.freifunk.net/anleitungen/konfigurationsmodus-erneut-aufrufen/

ggfs. noch ein Bsp. von dem ssh login: ssh root@10.185.0.1

-> Added.
