### ISSUE TITLE
Aufräumen site-fffd Konfiguration für gluon branches

### ISSUE THREAD

**Issue by indigo423** [freifunk-fulda/orga#56]
Es muss sicher gestellt werden, dass die gluon branches auch die richtigen branches von den site-fffd submodulen einbinden. Die "Testing" firmware muss in allen branches zur Verfügung stehen.

**Comment by indigo423** [comment]
Lösungsvorschlag in PR freifunk-fulda/site-fffd#1

**Comment by SISheogorath** [comment]
solved with https://github.com/freifunk-fulda/site-fffd/pull/6
