### ISSUE TITLE
Autoupdater für development deaktivieren

### ISSUE THREAD

**Issue by indigo423** [freifunk-fulda/orga#57]
Für die Installation der Firmware aus development soll die Autoupdate funktion deaktiviert werden. In Testing und Stable soll die Funktion weiterhin aktiviert bleiben.

**Comment by indigo423** [comment]
Lösungsvorschlag in PR freifunk-fulda/site-fffd#2

**Comment by SISheogorath** [comment]
solved with https://github.com/freifunk-fulda/site-fffd/pull/6
