### ISSUE TITLE
Remove gluon fork from freifunk-fulda

### ISSUE THREAD

**Issue by SISheogorath** [freifunk-fulda/orga#58]
While working on a working gluon build  with version 2015.1.2 already metioned it's a bit pointless to have that gluon fork in our repos because it's only an "update fork". Means: We only merge changes from original gluon repo, merging our sites config (and yes, @reissmann you already said it, it's such a dump) and having trouble checking out the right commits etc. So we've tested to change the build process to do that checkout by script via buildsystem. It works so we can use the freifunk-gluon repo and remove ours. 
Good points:
- less work about keep everything up-to-date
- simplify build process

Bad points:
- Build process outside of the buildsystem is not as simple because not all docs are not done yet

Everything important can be found in #44

**Comment by fooker** [comment]
The development build is now directly based on upstream gluon. Jenkins is managing the checkout of the right version.
