### ISSUE TITLE
Marketing zum Thema Freifunk

### ISSUE THREAD

**Issue by SISheogorath** [freifunk-fulda/orga#59]
Ich habe mir heute so überlegt, dass man fernab des Technischen ggf. mal mehr marketing betreiben sollte. Hier bieten sich ja all die Feste die man so kennt durchaus an. Interessant würde ich es finden, wenn man mal irgendwelche lokalen Künstler oder angehende Künstler anspricht und eben Auffordert, unsere Router zu "verschönern". Ich denke mal solch ein TP-Link könnte sich durchaus als kreative Spielwiese entpuppen und andere Communities passiert das sogar schon.

So individualisierte Router könnte man dann auch an festlichen Veranstaltungen oder ähnlichem einfach ausstellen bzw. eben zur Mitnahme anbieten. Das würde zum einen den Künstlern helfen und zum anderen uns. Natürlich ist der Router dann schon mit unserer Firmware vorgeflasht und bereit zum Einsatz. Generell wäre wohl mehr präsenz insgesamt sinnvoll. 

Außerdem sollten wir eben nochmal wirklich neue Flyer entwickeln und das alles möglichst zeitnah, denn gerade jetzt im Sommer sind eben die meisten Feste und Veranstaltungen, außerdem ist es angenehmer als bei -18°C draußen zu sitzen ;)

Eine weitere Idee wäre nun in kürzester Zeit eben möglichst viel auszurollen, also eine echte Marketing offensive in der Richtung zu ermöglichen. Da könnte man sich sicher noch einige Aktionen einfallen lassen. Diese könnte/sollte man dann vielleicht auch direkt mit dem City-Marketing abstimmen.

Nun ja, sind gewiss alles Punkte, wo man sagen dürfte "Joa, prima, lass uns das machen" allerdings wie das immer so ist, ist "uns" meist erstmal alle anderen. Deswegen würde ich hier wirklich Vorschlagen ein Projektmanagement zu starten mit Fälligkeitsdatum und konkret Arbeiten aufteilen. Natürlich braucht das Leute die Mitmachen. Jemand der sagt "Flyerredesign kümmere ich mich drum" und eben auch einen konkreten Stichtag "Der 3. Freitag nach dem 5. Vollmond des Jahres bei Sonnenuntergang" wann es fertig sein muss. Im Moment sind wir bei vielen Dingen sehr in der Richtung "machen wir dann" unterwegs und "dann" ist irgendwann in den nächsten 2 Stunden bis Jahren. Und das ist vermutlich häufig unser Problem. Mehr Meilensteine, mehr Einsatz, mehr Freifunk :) So let's go on and do it!

**Comment by mfuhrmann** [comment]
### Zum Thema Kontakte:

Ich habe schon mal ein wenig recherchiert und potentielle Kontakte mit denen ich anfangen würde gesammelt. Falls euch noch etwas dazu einfällt, bitte hinzufügen.

Die Frage die mir sich stellt ist: Wie gehen wir an diese Kontakte ran? Anschreiben per Brief? Email? Telefon? Klinken putzen?
1. Städte/Gemeinden
   - http://www.landkreis-fulda.de/landkreis-intern/staedte-und-gemeinden.html
2. Vereine
   - Feuerwehr: http://www.fulda.de/stadtverwaltung/feuerwehr-fulda/freiwillige-feuerwehr.html
   - Schützenvereine:
     http://www.schuetzenkreis61.de/Vereine.pdf
     http://www.klicktel.de/branchenbuch/fulda/fitness-und-sport/sport/schuetzenverein/091564749
   - Musikvereine: http://www.musikverband-fulda.de/mitgliedsvereine.html
   - Kleingärtnervereine: http://www.klicktel.de/branchenbuch/fulda/verein-verband-und-organisation/verband/kleingaertnerverein/431772933
3. Eventschmieden:
   - Eventdienstleister: http://www.gelbeseiten.de/event/fulda
4. Jugendherbergen
   - Fulda: http://www.djh-hessen.de/jugendherbergen/fulda/
5. Frisöre oder Gastronomie können direkt angesprochen werden, wenn man dort als Gast ist

### Zum Thema Kunst:

Wenn das künstlerische schon bei anderen existiert, besteht doch bestimmt die Möglichkeit, dass wir das übernehmen können, oder?
Wie genau definiert sich "verschönern"? Aufkleber? Andere Gehäuse? Bierkisten-WLAN Router? Link doch mal etwas dazu. 

### Zum Thema Flyer/Poster:

~~Ich habe den Flyer angepasst. Ich schaue mal, ob es dazu ein Ticket gab und werde einen Pull Request dafür erstellen. (edit: https://github.com/mfuhrmann/fffd-artwork/blob/master/Flyer/fffd_flyer_Ansicht.pdf )
Auch am Poster bin ich (bzw. meine Bekannte dran).~~

**Comment by reissmann** [comment]
Bin dafuer.

**Comment by mfuhrmann** [comment]
Der Flyer ist aktuell. Siehe hier: https://github.com/freifunk-fulda/fffd-artwork/blob/master/Flyer/fffd_flyer_Ansicht.pdf
Das Thema kann also hier raus.
Ob wir einen Neuen wollen? Bestimmt. Davor käme allerdings die Logofrage befürchte ich. Beides gehört auf jeden Fall in das Artwork Repo.

**Comment by SISheogorath** [comment]
Kann auf Treffen weiter besprochen, vorerst closed
