### ISSUE TITLE
Generate new ULA Prefix

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#6]
We should generate a pseudo-random ULA, as claimed in RFC 4193

**Comment by reissmann** [comment]
https://www.sixxs.net/tools/grh/ula/

**Comment by reissmann** [comment]
Please welcome our new ULA: fd00:65a8:93a4::/48

It is registered to maglab e.V. 
https://www.sixxs.net/tools/whois/

**Comment by fooker** [comment]
Fixes on latest development and on gw03.
