### ISSUE TITLE
IRC Link auf Webseite ändern

### ISSUE THREAD

**Issue by mfuhrmann** [freifunk-fulda/orga#60]
Hier unter **Kontaktmöglichkeiten**: https://fulda.freifunk.net/kontakt/ steht noch der alte IRC Link.

Vielleicht sollte wie auf der Startseite auch dieser Link: https://kiwiirc.com/client?settings=439e1e95b483c4f963ff377e518cfc0f dorthin?

**Comment by fooker** [comment]
Ich bin da kein großer Freund von. Für jeden der einen IRC Client installiert hat funktioniert das auch ohne kiwiirc. Wir verlinken ja auch auf mailto: ohne eine web-implementierung vorzuschalten.

## 

-----Original Message-----

**Comment by mfuhrmann** [comment]
Damit hast du Recht. Aber der 0815 User, der sich im Freifunk Projekt involvieren möchte, hat es damit einfacher. IRC Clientsoftware ist nun mal keine Standardausrüstung.
Keine Ahnung wie wir damit umgehen sollen. Ich selbst mag die Kiwi Lösung an der Arbeit, weil ich keine  Ports für IRC in der Firewall offen habe.

**Comment by SISheogorath** [comment]
Moin,

Was spricht denn dagegen den IRC Link zu belassen und darunter einen Eintrag "Web-Chat" zu packen und dort KiwiIRC zu verlinken? Ist denke ich eine saubere Lösung. 

Auf der Frontpage sollte man denke ich den KiwiIRC Link lassen, weil das wohl eine der ersten Aufschlagsseiten sein Wird wo gerade unbedarfte User drauf drücken. Die Daten stehen im KiwiIRC ja auch seitlich drin, von daher sollte eigentlich jemand, der IRC Links nutzen kann auch das hinbekommen.

Eine Anmerkung noch: der IRC-Link nutzt `irc://` das ist aber per default die plain connection. heißt non ssl per 6667. Der maglab Channel ist aber SSL only. Heißt über den IRC Link kommt man eigentlich gar nicht rein. Zumindest nicht ohne Händisch nach zu bessern.

**Comment by SISheogorath** [comment]
Ich habe den Link auf `ircs://irc.hackint.org:9999/mag.lab` umgestellt. Außerdem darunter noch einen Link zum KiwiIRC von Hackint [1] eingestellt. Außerdem wurde der Link auf der Haupseite nochmal auf die KiwiIRC-Instanz von Hackint [1] angepasst, sodass wir hier nicht mehrere verschiedene Anbieter haben. Da die Zertifikatsprobleme bei Hackint gelöst sind, stellt es auch für Enduser kein Problem mehr dar.

[1] https://webirc.hackint.org/#mag.lab
