### ISSUE TITLE
Add faster/other authentication and encryption options for mesh VPN

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#63]
Currently we are using salsa2012+gmac as encryption/authentication method.

Switchung to salsa2012+umac should give us a performance boost. See https://projects.universe-factory.net/projects/fastd/wiki/Benchmarks

With 2015.1.x there is an option allowing the user to configure the methods used. With this we should support the null option for encryption leading to: null+salsa2012+umac

**Comment by reissmann** [comment]
This is exactly what I was planning. 
However, I'm not sure if it is a good idea to let users choose. It will either give a wrong understanding of security or unsettle users by asking them to make technical decisions.

**Comment by fooker** [comment]
I hope it's a advanced option, almost hiiden. I will do a test build with this option enabled to get a view on how the interface is looking for this and provide additional information.

**Comment by fooker** [comment]
![gluon-enc-opts](https://cloud.githubusercontent.com/assets/405105/9451340/56d275d6-4aae-11e5-9ad1-5b6afa7a4161.png)
This is how the interface looks like. It's part of the expert config called "Mesh VPN".

**Comment by fooker** [comment]
To make this work, we need to add the method to the gateways and add i18n for the texts.

**Comment by SISheogorath** [comment]
maybe you want to use https://github.com/freifunk-fulda/site-fffd/pull/7

**Comment by fooker** [comment]
Fixes latest development.
