### ISSUE TITLE
Vorteile eines freien Netzwerk auflisten

### ISSUE THREAD

**Issue by mfuhrmann** [freifunk-fulda/orga#64]
Ich hatte ein Gespräch mit Indigo über die Thematik "freies Netzwerk". Ich bin der Meinung, dass diese Vorteile (ich könnte Sie selbst gar nicht alle nennen), in einer schön formulierten Weise auf die Webseite gehören. Das ist ein wichtiger Punkt, denn oft wird man gefragt: Was habe ich denn von einem eigenen Netzwerk? Einfach nur "Du kannst machen was du willst" oder "Free Wifi" genügt da leider nicht um zu Punkten.

Ggfs. können wir hier schon mal Punkte zusammentragen.

**Comment by mfuhrmann** [comment]
Einen allgemeinen Text habe ich dazu: https://docs.google.com/document/d/1N2J6rP726bdmD4bFdVDzc_QLobvhGERE53M2Dwsky6s/edit#heading=h.2q821s7qqpbj
("Warum wird Freifunk gebraucht?").
Genügt das für's Erste?

**Comment by SISheogorath** [comment]
- Höhere Ausfallsicherheit - Betreibt jeder einen eigenen Knoten, bringt der ausfall eines einzelnen Knotens nicht das gesamte Netzwerk in Gefahr
- Volle Bandbreite - Es gibt keine künstlichen Grenzen, die Benutzer anhand ihrer Liquidität den Netzzugang einschränken
- Regionalität - Eine regionale Vernetzung stärkt die Region, ihre Bürger und Betriebe und ermöglicht besondere Angebote.
- Know-How-Transfer - Durch den Aufbau eines dezentralen Netzes beschäftigt sich jeder bewusster mit den Technologien des Internets und erlernt so die Grundlagen der heutigen vernetzten Welt.
- Gemeinschaft - Ein freies Netzwerk funktioniert nicht ohne Gemeinschaft und Zusammenarbeit. Es bringt also Menschen zusammen, die es gestalten wollen
- Kreativität - Ein freies Netzwerk mit einer aktiven Gemeinschaft ermöglicht neue ansätze zu verfolgen und Ideen zu entwickeln
- Zukunft - Freie Netze ermöglichen uns eine andere Zukunft als ein rein komerzieller Internetbetrieb

**Comment by mfuhrmann** [comment]
+1
Das sollte definitiv mit auf die neue Homepage!

**Comment by SISheogorath** [comment]
Ein bisschen muss man noch dran feilen.

Mit Stärkung der Region kann man viele Leute gewinnen. Wenn man das richtig verpackt und den richtigen Leuten zuwirft, lässt sich da bestimmt was bewegen.

**Comment by SISheogorath** [comment]
Kann auf Treffen weiter besprochen werden und/oder im geschlossenen Zustand erweitert werden
