### ISSUE TITLE
Android App auf Webseite verlinken

### ISSUE THREAD

**Issue by mfuhrmann** [freifunk-fulda/orga#65]
Da wir nun auch in dieser App gelistet sind
https://play.google.com/store/apps/details?id=de.appwerft.freifunker
könnte man die App auf unserer Website verlinken

**Comment by mfuhrmann** [comment]
Sheogorath hatte die Idee, so einen "Playstore Download Button", wie man ihn des öfteren auf Webseiten sieht auf der Webseite zu integrieren.
Dieses Plugin scheint ggfs. dafür geeignet zu sein: https://wordpress.org/plugins/google-play-store-badge/

**Comment by SISheogorath** [comment]
Ich habe es ohne ein Plugin einfach mithilfe von etwas plain HTML und einem Generator [1] realisiert. Die App wurde auf der Haupseite eingebunden und sollte, sobald für andere Plattformen wie iOS, Windows und Ubuntu Phone weitere Apps zur verfügung stehen, ensprechend ergänzt werden.

[1] https://developer.android.com/distribute/tools/promote/badges.html
