### ISSUE TITLE
"How it works" Karte aktualisieren

### ISSUE THREAD

**Issue by mfuhrmann** [freifunk-fulda/orga#66]
Die Meshkarte zeigte noch die SSID freifunk-fulda.de an. Ich habe die aktualisierte Version aus meinem Pull Request (https://raw.githubusercontent.com/mfuhrmann/fffd-artwork/master/Map/fffd_map.png) bereits im Wordpress eingespielt bzw. ausgetauscht. Siehe hier: https://fulda.freifunk.net/was-ist-freifunk/

**Comment by fooker** [comment]
Es gibt aber noch keinen Router der diese SSID ausstrahlt, oder?

**Comment by mfuhrmann** [comment]
Wenn du es nicht weißt, wer dann?
Habe es rückgängig gemacht, aber das neue Bild schon hochgeladen, damit, wenn es soweit ist, schnell umgeschaltet werden kann.

**Comment by fooker** [comment]
Das ist doch gerade das Ding an freien, dezentralen Projekten. Firmware forken, SSID ändern und router flashen. Schon gibt es diese SSID ganz ohne mein zutun.

Ich will diese zentrale Instanz nicht sein. Deswegen frage ich, in der hoffnung auf Diskurs, anstatt das zu behaupten oder zu propagieren.

**Comment by SISheogorath** [comment]
Im Moment nutzt noch niemand die neue SSID. Siehe #38 

Sollte sie wirklich schon wer ausstrahlen nutzt er keine site-config von uns.

**Comment by mfuhrmann** [comment]
Dann passt ja jetzt alles :-)

**Comment by mfuhrmann** [comment]
Wurde von irgendwem erledigt. Auf der Webseite ist die neue Version.
