### ISSUE TITLE
Einführung von SaltStack als SCM auf gw01 & gw02

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/orga#67]
Um die Konfiguration aller Server an einer zentralen Stelle verwalten zu können sollten wir ein Software-Configuration-Management eingeführt werden.

Hierfür eignet sich SaltStack, welches bereits auf gw03 verwendet wird. Dies sollte auch auf gw01 und gw02 übertragen werden.

**Comment by mortzel** [comment]
Da die SaltStack Installation auf gw03 bereits eine neue MTU sowie B.A.T.M.A.N Version besitzt, können gw01 und gw02 erst nach dem Release der Firmware v3 auf SaltStack umgestellt werden.

Siehe:
- MTU #35 
- ULA #6

**Comment by reissmann** [comment]
done. siehe freifunk-fulda/saltstack-config
