### ISSUE TITLE
Installieren des Salt-Masters auf einem Server mit öffentlicher IP-Adresse

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/orga#68]
Da SaltStack als SCM verwendet werden soll [1] um die Konfiguration und Installation von Servern zu erleichtern, wird ein Salt-Master benötigt.

Mit Hilfe von Salt kann aus einem normalen Server ein Freifunk-Gateway erstellt werden. Daher sollte dieser Salt-Master unter einer öffentlichen IP-Adresse erreichbar ein.

[1] siehe #67

**Comment by mortzel** [comment]
Eventuell könnte man sich hierfür einen Raspberry Pi 2 kaufen und in kostenlos in einem Rechenzentrum [1] hosten. Kosten für einen Pi 2 mit 32GB SD 32GB Stick und Gehäuse lägen etwa bei 80€. Hiervon könnten etwa 50€ durch durch die Förderung des AStA gedeckt werden.

[1] http://raspberry-host.de/

**Comment by fooker** [comment]
Der Salt-Master befindet sich gerade auf srv1 und ist damit für alle Admins zugänglich.
