### ISSUE TITLE
Privates Git-Repo für die Versionierung der Salt-States erstellen

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/orga#69]
Um die Salt States und Pillars, welche für Issue #67 erstellt werden zu managen sollte ein Git-Repo erstellt werden, welches diese Dateien enthält. 
Hierbei enthalten die Pillars sensible Daten, die nicht öffentlich zugänglich sein sollten. Daher sollten diese Daten in einem Privaten Repository abgelegt werden.

**Comment by fooker** [comment]
Ich bin gerade über den saltstack gpg renderer [1] gestolpert. Damit lassen sich Teile des pillars mit dem Key-Pair des saltstack-masters verschlüsseln. So können wir auch sensieble Daten in einem öffentlichen Repo ablegen.

Mit einem öffentlichen Repo können wir andere ermutigen ein eigenes Gateway zu betreiben und wir können Test-Gateways aufsetzen.

[1] https://docs.saltstack.com/en/stage/ref/renderers/all/salt.renderers.gpg.html

**Comment by fooker** [comment]
Die config ist jetzt sogar öffentlich zugänglich: https://github.com/freifunk-fulda/saltstack-config
