### ISSUE TITLE
Generate random MAC addresses

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#7]
MAC addresses should be pseudo-random:

printf '%02x:%02x:%02x:%02x:%02x:%02x\n' $(((($RANDOM % 256) | 2) & 0xfe)) $(($RANDOM % 256)) $(($RANDOM % 256)) $(($RANDOM % 256)) $(($RANDOM % 256)) $(($RANDOM % 256))

**Comment by reissmann** [comment]
Knotenseitig: Fixed in development-38
Backend: ToDo

**Comment by fooker** [comment]
Still missing in firmware for BSSID.

**Comment by reissmann** [comment]
backend done.

**Comment by fooker** [comment]
According PRs: https://github.com/freifunk-fulda/fffd-packages/pull/4 and https://github.com/freifunk-fulda/site-fffd/pull/21

**Comment by mortzel** [comment]
changed mac on srv2

**Comment by fooker** [comment]
Can be done in combination with #144.

**Comment by fooker** [comment]
Done
