### ISSUE TITLE
Zentrales Benutzerverzeichnis

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/orga#70]
Da wir mittlerweile auf mehreren Systemen verschiedene Logins verwalten wäre es sinnvoll ein zentrales Benutzerverzeichnis für Freifunk-Fulda und Mag.Lab zu nutzen. 

Soll dies realisiert werden oder nicht und wenn ja wie ??

**Comment by Jo-Jo0** [comment]
Erledigt, da Mag.Lab und Freifunk Fulda sich trennen und Mag.Lab (vermutlich) bald LDAP nutzt
