### ISSUE TITLE
Umstellen der internen DNS-Domain auf eine echt Domain

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/orga#72]
Da unser Netz offen ist, ist es auch po­ten­zi­ell unsicher. Da aber auch Services inerhalb des Freifunk Netzes betrieben werden sollen, sollten diese mit SSL abgesichert werden. Da unsere Domain '*.fffd' jedoch keine echte Domain ist können wir keine geprüften SSL Zertifikate, die keine Warnung bei dem Nutzer erzeugen, beantragen.

Daher soltlen wir uns eine kurze Domain wie fffd.io sichern und diese intern verwenden. 

Hierdurch würden jedoch zusätzliche Kosten entstehen und nur die Betreiber der Domain können SSL Zertifikate beantragen.

**Comment by SISheogorath** [comment]
Probleme bei der Zertifizierung können ebenfalls auftreten. 

Soweit ich es bisher mitbekommen habe, prüft z.B. StartSSL eine Webseite. Speziell dort ist mir auch ein Fall bekannt, wo die Zertifikatsvergabe aufgrund eines Spendenbuttons abgelehnt wurde. (allerdings ging es um ein Level 1 Cert)

Dadurch dass unsere Dienste dann jedoch vorwiegend intern erreichbar sind, bin ich unsicherer, ob wir ausreichend Zertifikate ausgestellt bekommen. Grundsätzlich teile ich die Überlegung.

**Comment by mortzel** [comment]
Vorschläge für eine Domain:

fffd.io -> 69,90€/a
fffd.it -> 11,90€/a
fffd.sh -> 69,90€/a
fffd.to -> 77,35€/a

**Comment by mortzel** [comment]
Netcup hat aktuell ein Angebot für .eu Domains für nur 4,92€ pro Jahr
http://www.netcup-sonderangebote.de/domains/aktion-neuregistrierung-rabatt-eu-domain/

Und das beste ist, dass die Domain fffd.eu noch frei ist.

**Comment by fooker** [comment]
+1

**Comment by SISheogorath** [comment]
Ich hab in den letzten Wochen recht viel darüber philosophiert und nachgedacht, was an der Netzstruktur schräg ist und warum.

Eines der Ergebnisse war, dass man interne dienste gar nicht unter einer .fffd Adresse anbieten möchte. die Gründe dafür sind uns allen Klar und wurden ja auch hier schon beleuchtet. Allerdings glaube ich liegt noch ein ganz anderes Problem vor, wenn wir nun mit einer offiziellen Domain arbeiten: 
- Wer bestellt sie?
- Wem gehört sie?
- Wie regelt man eine Übergabe?
- An wen muss man sich für einen Eintrag wenden?

Das DNS sehr zentralistisch ist, wissen wir alle. Die Frage ist eben, wie will man interne Domains ausreichend dezentral verwalten, damit es sauber funktioniert?
Wäre nicht die bessere Variante wenn sich die Dienstanbieter einfach mit irgendeiner eigenen offiziellen Domain "begnügen"? Hier hat es eben den Vorteil, dass es eben echt-dezentral ist. 

Nimmt man diesen Fall nun als gesetzt an, wäre die nächste Frage: Wozu braucht man denn überhaupt die interne DNS Domain? Hauptsächlich für eigene Dienste wie den Meshviewer, die interne Serveradressierung für SSH usw. und sonstige Anwendungen die eigentlich keinen Login benötigen. Somit ist SSL zwar toll, aber nicht wirklich notwendig.

Ich möchte damit nicht sagen, dass wir diese Umstellung nicht tun sollten, aber wenn wir sie tun, sollten die oben genannten Fragen, geklärt werden.

**Comment by mortzel** [comment]
Da die Domain vorerst nur intern verwendet werden soll, ist es eigentlich egal auf wessen Namen sie registriert wird. Eine Möglichkeit wäre hier den bereits vorhandenen Netcup Account des mag.lab/FFFD zu nutzen, den auf diesen haben mehrere Personen Zugriff.

Die interne Domain soll für alle DNS-Auflösungen innerhalb unseres Netzes genutzt werden. Dies umfasst neben den von uns betriebenen Services auch alle Seiten und Anwendungen, die von Nutzern des Netzes betrieben werden.

Auch wenn der Meshviewer kein Login benötigt sollte dieser in einem potenziel unsicherem Netz mit einer verschlüsselten Verbindung betrieben werden.

**Comment by mortzel** [comment]
Die Domain `fffd.eu` ist nun gekauft und es kann mit der Umstellung begonnen werden.

**Comment by reissmann** [comment]
done.

**Comment by mortzel** [comment]
Einträge müssen noch in verschiedenen anderen Repos angepasst werden.
- freifunk-fulda/icvpn-meta
- freifunk-fulda/site-fffd

**Comment by SISheogorath** [comment]
New Domain was added to API

**Comment by fooker** [comment]
See https://github.com/freifunk-fulda/site-fffd/pull/25 for related firmware changes.

**Comment by fooker** [comment]
Merge to development

**Comment by reissmann** [comment]
Sadly, the solution we used to choose is not working out. As our own nameservers are not authoritive for the domain fffd.eu, any request for internal domains by anyone other than our own clients will fail.

**Comment by fooker** [comment]
Related: #143

**Comment by mortzel** [comment]
The domains fulda.freifunk.net and fffd.eu run now both on our nameservers
