### ISSUE TITLE
Disabling Client Wifi doe not disable Client Wifi aliases

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#73]
The latest firmware allows to disable the client WiFi using the config interface. Disabling the WiFi does not disable the tha alias networks.

**Comment by fooker** [comment]
I disabled the wifi config module for now and delay the fix for v4.

**Comment by fooker** [comment]
By consens: delay to v5

**Comment by mortzel** [comment]
Wifi Alias was removed in Firmware v5
