### ISSUE TITLE
Rename Mesh SSID

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#75]
The mesh SSID is currently set to the (wrong / old) BSSID. It should be changed to something meaningfull and to the same on 2.6 and 5 GHz.

**Comment by fooker** [comment]
I would like to change this at the same time as the BSSID is changed (see #7).

As a SSID I would like to propose 'mesh.fulda.freifunk.net'. Feedback on this is very welcome.

**Comment by fooker** [comment]
According PRs: https://github.com/freifunk-fulda/fffd-packages/pull/4 and https://github.com/freifunk-fulda/site-fffd/pull/21

**Comment by rubo77** [comment]
I wouldn't recomment such a misunderstandable ssid for the underlying mesh network. If unexperienced users see the ssid 'mesh.fulda.freifunk.net' they think, they can connect to it and get a bad user experience not being able to connect.

The ssid for the batman network always should by cryptic, so the users don't try to use it on their client devices

**Comment by fooker** [comment]
Maybe we can call it "T-Offline" ore something similar ;)

**Comment by fooker** [comment]
Can be done in combination with #144.

**Comment by fooker** [comment]
Done
