### ISSUE TITLE
Dynamische bzw. Zeitgesteuerte Bandbreitenbegrenzung

### ISSUE THREAD

**Issue by mfuhrmann** [freifunk-fulda/orga#76]
Kleine Idee, die mir in Zusammenarbeit mit Gewerbetreibenden in den Sinn kam.

Die Bandbreitenbeschränkung ist sehr praktisch. Firmen kann das mitunter -tagsüber- wichtig sein. Außerhalb der Arbeitszeiten sieht es anders aus. 

Es wäre zu prüfen, ob man die Beschränkung generell variabel machen kann und ob es sich hübsch in den Konfigmodus integrieren lässt.

**Comment by SISheogorath** [comment]
Also Grundsätzlich kann man im aktuellen Stable-, ebenso wie im Testing-Release eine Bandbreitenbeschränkung aktivieren. Im Moment ist sie allerdings statisch. 

Im Stable-Release erscheint diese Option sobald man Mesh über VPN im einfachen Modus aktiviert.

**Comment by fooker** [comment]
Ich bin da etwas geteilter Meinung. Es währe schön nachts die freien Resourcen nutzen zu können. Andererseits besteh die Gefahr, dass die einstellungen tagsüber dann noch limitierender getroffen werden.

**Comment by fooker** [comment]
We don't propose the limiting at all. Therefore we should encourage people to add more resources instead of giving more options to limit them.
