### ISSUE TITLE
Konfigmodus erweitern / WLAN "zeitschalten"

### ISSUE THREAD

**Issue by mfuhrmann** [freifunk-fulda/orga#77]
Einige Privathaushalte haben desöfteren Bedenken wegen der WLAN Strahlung und wollen diese nicht Nachts um sich herum haben.

Es wäre super, wenn man WLAN ein/aus über einen Scheduler im Konfigmodus einstellen könnte.

**Comment by fooker** [comment]
Ich glaube, das Aufklärung hier das bessere mittel ist. Den Zugang zu einem freien Netz an den eigenen Tagesrythmus zu koppeln wiedersprich IMHO der Idee. Im schlimmsten fall trennt man damit halt einen Teil des Meshes ab.

Wenn die Leute sowas wirklich haben wollen, sollen sie sich halt eine Zeitschaltuhr kaufen. Dann spart man wenigstens den Stromverbrauch der Node mit ein.

**Comment by mfuhrmann** [comment]
Da gebe ich dir Recht. /closed
