### ISSUE TITLE
Informationssammlung: "Hohe Punkte" in Fulda

### ISSUE THREAD

**Issue by mfuhrmann** [freifunk-fulda/orga#79]
Sven hatte mir von einem 360° Freifunk "Schirm" an einem Turm/Mast in einer anderen Stadt erzählt. Dieses Issue soll dazu dienen, mögliche Lokationen in Fulda zu listen. Ggfs. kommt man mit den Besitzern irgendwie ins Gespräch oder jemand kennt jemanden, der jemanden kennt...
- Prinzipiell weiß ich nicht wie hoch so ein Punkt sein sollte. In der Innenstadt könnte daher jedes Gebäude ab einer gewissen Höhe in Frage kommen. Z.B. Galeria Kaufhof, Holiday Inn, Beate Uhse usw. Falls Ihr also Hausbesitzer in der Innenstadt kennt...
- Jumo Mess- und Regeltechnik - Der Turm mit der Temperaturanzeige: https://www.google.de/maps/place/JUMO+GmbH+%26+Co.+KG/@50.5629656,9.6846525,17.5z/data=!4m5!1m2!2m1!1sUMO+GmbH+%26+Co.+KG++Moritz-Juchheim-Stra%C3%9Fe+1!3m1!1s0x47a336814a5d4b7f:0x46b48ed6f04683e8
- Fulda Reifen - Backsteinschornstein: https://www.google.com/maps/place/K%C3%BCnzeller+Str.+61,+36043+Fulda,+Deutschland/@50.54695,9.69241,19z/data=!3m1!4b1!4m2!3m1!1s0x47a3369608e48c75:0x1b7a619a761f71e5
- GWV - Backsteinschornstein: https://www.google.com/maps/place/Bonhoefferstra%C3%9Fe+30,+36037+Fulda,+Deutschland/@50.56486,9.69994,19z/data=!3m1!4b1!4m2!3m1!1s0x47a3368a3c91fbf9:0x51a1ef5808504363
- ? Rhönenergie ? - Schornstein: https://www.google.de/maps/place/Frankfurter+Str.+4,+36043+Fulda/@50.5451017,9.6750735,247m/data=!3m2!1e3!4b1!4m2!3m1!1s0x47a336a1aae97715:0x8b8df1cd4f76ccca
- "Da bei dem Harley Davidson Laden" - Turm-Bürogebäude: https://www.google.de/maps/place/Heidelsteinstra%C3%9Fe+6,+36043+Fulda/@50.5438247,9.6918501,410m/data=!3m1!1e3!4m2!3m1!1s0x47a336be7ee6e5c1:0x4deddbe1c9be045c
- Hotel Badehof, Bad Salzschlirf - Backsteinschornstein: https://www.google.de/maps/place/Hotel+Badehof/@50.6215685,9.5034168,249m/data=!3m1!1e3!4m2!3m1!1s0x0000000000000000:0x435a73c526faad79!6m1!1e1
- Osthessencenter - Hochhäuser: https://www.google.de/maps/place/Fulda/@50.5491723,9.6853088,207m/data=!3m1!1e3!4m2!3m1!1s0x47a33449e9f9b92d:0x422435029b0ab30!6m1!1e1
- Amt für Straßen- und Verkehrswesen Fulda - Hochhaus: https://www.google.de/maps/place/Gesundheitsamt+Fulda/@50.5516488,9.7023604,15z/data=!4m2!3m1!1s0x0:0xb09fb87737093dc5?sa=X&ved=0CHcQ_BIwCmoVChMI-Le-rr-KyAIVQzsaCh3vGQis
- Fulda Galerie - Airfield Tower: https://www.google.de/maps/place/Airfield+7527,+36041+Fulda/@50.54195,9.64038,415m/data=!3m2!1e3!4b1!4m2!3m1!1s0x47a3346d0f99e8a9:0x5ee1ea571610ccf8
- Hochhaus nähe Klinikum: https://www.google.de/maps/place/Dr.-H%C3%B6fling-Stra%C3%9Fe+2,+36043+Fulda/@50.55038,9.71189,247m/data=!3m2!1e3!4b1!4m7!1m4!3m3!1s0x47a3346d0f99e8a9:0x5ee1ea571610ccf8!2sAirfield+7527,+36041+Fulda!3b1!3m1!1s0x47a336ef3005efc1:0x5469da5cfe828884
- Lioba Kirche Petersberg - https://www.google.de/maps/@50.5613916,9.7121489,205m/data=!3m1!1e3
- Hochhaus neben Heinrich von Bibra Schule: https://www.google.de/maps/place/Buseckstra%C3%9Fe+2,+36043+Fulda/@50.5474217,9.6789175,357m/data=!3m2!1e3!4b1!4m2!3m1!1s0x47a33698a89c1f25:0x9e0df448a2d0111a
- Neuenberg - Gute Aussicht über Fulda- Am Heiligenfeld / Hoherodskopfstraße: https://www.google.de/maps/place/Hoherodskopfstra%C3%9Fe+16,+36041+Fulda/@50.5482734,9.6573613,17z/data=!3m1!4b1!4m7!1m4!3m3!1s0x47a33417f74d1685:0x3bacca0fd8ba1241!2sAm+Heiligenfeld+3,+36041+Fulda!3b1!3m1!1s0x47a3341804d20a77:0x6cf42b59a07aedc7
- Hochhaus in Neuenberg: https://www.google.de/maps/place/An+St.+Florian+2,+36041+Fulda/@50.5471224,9.6619224,492m/data=!3m2!1e3!4b1!4m7!1m4!3m3!1s0x47a3341804d20a77:0x6cf42b59a07aedc7!2sHoherodskopfstra%C3%9Fe+16,+36041+Fulda!3b1!3m1!1s0x47a33418eb00354f:0x5a35c10b06f193de
- Ziehers Nord, Hochhäuser, Von Galen Str. 20,47,49: https://www.google.de/maps/place/Sportbad+Ziehers/@50.5667307,9.6968001,292m/data=!3m1!1e3!4m2!3m1!1s0x47a3368dc05a6a65:0x4ff79f75a005cdfe!6m1!1e1
- Edelzell, "Zum Rhönlingswald": https://www.google.de/maps/place/Zum+R%C3%B6hlingswald,+36043+Fulda/@50.5237887,9.6908607,17z/data=!3m1!4b1!4m2!3m1!1s0x47a3313542d027df:0x28442bbb1d29c920
- Am alten Schlachthof - Schornstein: https://www.google.de/maps/place/50%C2%B033'04.6%22N+9%C2%B040'11.5%22E/@50.5512779,9.6693238,174m/data=!3m2!1e3!4b1!4m2!3m1!1s0x0:0x0
- Gebäude am ZOB - https://www.google.de/maps/place/Am+Bahnhof+2,+36037+Fulda/@50.55382,9.6824066,17z/data=!3m1!4b1!4m2!3m1!1s0x47a3369bbbedc38b:0xf363f033c31084aa
- Maria Hilf-Kirche - https://www.google.de/maps/place/50%C2%B032'21.2%22N+9%C2%B042'13.2%22E/@50.5390759,9.7033536,146m/data=!3m1!1e3!4m2!3m1!1s0x0:0x0
- Antoniusheim Fulda - https://www.google.de/maps/place/antonius+%E2%80%93+Netzwerk+Mensch/@50.5551149,9.658505,586m/data=!3m1!1e3!4m2!3m1!1s0x47a3343b6b789735:0x9f3cae42343df94d!6m1!1e1

**Comment by mfuhrmann** [comment]
Ich habe diese Punkte mal auf http://osmtools.de/easymap eingetragen. Die Markerdateien lassen sich leider nicht hier einfügen. Anbei nur ein Screenshot.
![fffd_karte-hohe-punkte](https://cloud.githubusercontent.com/assets/4995222/11022111/02188726-8657-11e5-9104-013892c46982.png)

**Comment by Jo-Jo0** [comment]
Möglicherweise käme der Kirchturm der Maria-Hilf Kirche in Bachrain infrage. Von dort hat man Sichtkontakt nach Edelzell und kann Teile Fuldas und Künzells einsehen. Bei interesse kann ich gerne einen Kontakt herstellen

Die Koordinaten des Turmes lauten : 50.539218529, 9.703668952

**Comment by fooker** [comment]
This should be moved to the wiki.
