### ISSUE TITLE
IPv6 wird nicht zum VPN-Tunnel geroutet

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#8]
Das Gateway routet IPv6-Traffic nicht zum Exit-Tunnel-Interface.

**Comment by reissmann** [comment]
Das ist ein echtes Problem (und gleichzeitig das, was ich meinte, als ich sagte, dass wir die IPv6 Sachen nochmal genauer unter die Lupe nehmen muessen)!

Ist aber ein Problem der Gateways. Es fehlen vermutlich einfach die ip6tables Regeln, um den Traffic entsprechend zu behandeln.

**Comment by reissmann** [comment]
Closing, due to #39
