### ISSUE TITLE
Legacy SSID should be removed

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#81]
After a legacy support period, the old SSID should be removed.

This is a reminder issue.

**Comment by fooker** [comment]
We should come up with some content describing the what and why before we drop the SSID.

**Comment by fooker** [comment]
According PR: https://github.com/freifunk-fulda/site-fffd/pull/28.

**Comment by fooker** [comment]
Merge to development firmware. I' still unsure about the web content.

**Comment by reissmann** [comment]
fixed by v4 release
