### ISSUE TITLE
Private LAN

### ISSUE THREAD

**Issue by SISheogorath** [freifunk-fulda/orga#85]
Wie wäre es, wenn wir ein package basteln, welches ermöglichst, die LAN Ports am Freifunkrouter ähnlich dem "private wifi" zu nutzen? 

Hierbei würde ich allerdings das Ganze noch dahiongehend verändern, dass die Ports nicht einfach nur zum WAN Port bridgen, sondern auch ein Routing ins Freifunknetz ermöglichen.

Also alles was aus bestimmten privaten Adressbereichen (10.0.0.0/8 172.20.0.0/16 und 172.22.0.0/15) kommt, einfach ins Freifunknetz werfen, den Rest über das lokale Netz verteilen. Somit würde man das Freifunknetz nicht durch den externen Traffic belasten und hätte dennoch Zugriff auf alle internen Dienste. 

Das man dazu ein NAT verbauen muss, ist auch klar, aber ich denke, dass ist für solch ein Setup okay.

**Comment by fooker** [comment]
Den Bedarf für Private-LAN hatte ich auch schon einige male (es gibt noch erstaunliche viel alte T-Com-Hardware, die nur eine RJ45-Buchse besitzt).

NAT ins Freifunk-Netz ist eher schwierig. Dabei gilt es noch einiege Fragen zu klären:
- Welche implikationen hat eine IPv4-Adresse auf der Node
- Was passiert, wenn das private Netz gleiche Adressbereiche verwendet
- Wie bringt man den Clients im privaten Netz die Routen bei

**Comment by SISheogorath** [comment]
Ich würde sagen, gleiche IP Netze fangen wir einfach durch einen Hinweis ab und wer es dann immer noch probiert, merkt ja, dass es nicht klappt. Da können wir schließlich nicht viel tun. Oder man kann eben zwischen mit und ohne Freifunkzugriff per Option entscheiden.

bezüglich der Routen... mhm ja, stimmt... hab ich irgendwie quer gedacht und nicht daran, dass die ja ein anderes Standardgateway nehmen :D ich wollte eigentlich den Traffic Per IPtables einfach ins Freifunknetz schaufeln, wenn er über das Interface rauscht, aber klar, dazu müsste man eigentlich Gateways, sprich adressiert sein.

Die Lösung dafür ist wohl, das gesamte LAN Interface in ein NAT zu packen und einfach die Defaultroute über das normale wan interface zu legen statt durchs freifunknetz und die Freifunkrouten eben speziell abtrennen. DHCP haben wir eh auf den Knoten von daher sollte das nicht das Problem sein. Aber wirklich schön ist die Lösung nicht unbedingt :/

Dann viellicht doch einfach einen Bridge-mode, aber die Idee war halt, dass man das eigene Heimnetz trennen kann und dennoch zugriff auf Freifunkseiten hat. Dadurch könnte man eben auch mehr interne Dienste anbieten.

**Comment by reissmann** [comment]
Ich finde die Idee grundsaetzlich nicht gut.

1) Die Trennung der Netze auf dem Freifunk-Router finde ich extrem wichtig. Das bewerben wir auf die Weise und ich finde, dass das auch so bleiben sollte. Man koennte jetzt anfangen mit LAN -> Freifunk erlauben, aber Freifunk -> LAN verbieten. Man muss aber garantieren koennen, dass da keine Implikationen entstehen.

2) Nicht jeder WLAN-Router ist gleich. Bei einer Nanostation gibt es beispielsweise keine LAN-Ports.

3) Ich (und viele andere) nutzen die Netzbereiche bereits im LAN.

Am wichtigsten ist mir hier Punkt 1. Dinge die man im Configmode anklicken kann, werden auch angeklickt. Vielleicht waere es besser, eine Dokumentation zu erstellen, wie man eben genau das vorgeschlagene erreichen kann. Wenn dann jemand weiss, was er tut, ok.

**Comment by SISheogorath** [comment]
Okay, ja, kann ich nachvollziehen. Sehe ich so auch als Sinnvoll an. 

Ich denke, man wird hier auch schnell zu der Frage kommen, was genau wir in zukunft planen und wie wir uns selbst wahrnehmen. Aber das kann man denke ich besser auf dem nächsten Treffen besprechen, als hier in einem GitHub Issue.

Meine Intention dahinter war einfach, klar, ich möchte Freifunk Nutzen, aber ich möchte vielleicht auch auf meinen NAS zugreifen, der jetzt nicht unbedingt im ganzen Freifunk verfügbar sein soll. Allein schon, weil da meine Softwaresamlung offen drauf liegt und die so zu verteilen, wäre illegal. Und da es denke ich vielen so geht, war meine Idee eben wirklich man schafft ein privates Netzwerk welches dennoch Freifunkzugriff hat.

**Comment by fooker** [comment]
Der einzige Grund, den ich da sehe ist der, dass nicht mehr genügend Ports vorhanden sind um die Node anzuklemmen. Dabei sollten die Netzte aber trotzdem getrennt bleiben.

**Comment by mortzel** [comment]
Kann mit den folgenden Commands auf dem Konten gemacht werden:
```
uci set network.client.ifname=bat0
uci set network.wan.ifname='eth0 eth1'
uci commit network
```
Sollte man aber eventuell auch noch im Webinterface integrieren.

**Comment by reissmann** [comment]
Oder zumindest dokumentieren. Mein Vorschlag war damals mal, im Wiki
eine Kategorie mit lauter Anleitungen zu hinterlegen (z.B. wie monitore
ich meinen Knoten per SNMP, wie aktiviere ich private LAN, usw).

Man koennte das dann von hier aus verlinken (eine Sektion Anleitungen
gibt es dort schon): https://wiki.maglab.space/wiki/Freifunk_Fulda

-- 
PGP Key: https://0x80.io/pub/files/key.asc
PGP Key Fingerprint: DCB1 0B43 273C 0E23 5268  AD00 6461 2256 4468 FB98

**Comment by mortzel** [comment]
Eintrag wurde angelegt mit einem Link zur aktuellen Dokumentation von Gluon auf Github. Eigene Hacks können noch eingepflegt werden, bzw. die gängigsten aus der Dokumentation kopiert werden.
