### ISSUE TITLE
Current testing firmware has connection interrupts

### ISSUE THREAD

**Issue by SISheogorath** [freifunk-fulda/orga#87]
Our current testing firmware does often generates ping timeouts.

This has to be fixed before we can rollout the firmware as stable.

**Comment by SISheogorath** [comment]
I noticed the keyupload script is staying a long while in process table (used top on node)

I change the followoing line https://github.com/freifunk-fulda/fffd-packages/blob/testing/gluon-fffd-autokey/files/lib/gluon/gluon-fffd-autokey/fastd.conf#L1

back to "on connect" instead of "on connect sync" and the timouts stopped.

Building new firmware to validate the fix

**Comment by fooker** [comment]
We've assumed that the sync will block only the connection which is currently establesd. But it seems to be the case that the whole process is blocked including all active connections.

Therefore, I can verify the fix.

I've merged the fix to testing (and development) to get broader test coverage on that.

**Comment by SISheogorath** [comment]
is fixed
