### ISSUE TITLE
firmware.services.fffd ist von testing Knoten nicht erreichbar

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/orga#88]
Von testing Knoten, die GW03 verwenden, kann keine Verbindung zu firmware.services.fffd aufgebaut werden, daher funktioniert der Autoupdater nicht. Dies sollte vor dem Release gefixt werden, da sonst stable Knoten, die hinter testing Knoten hängen, kein Update machen können.

**Comment by fooker** [comment]
Sieht so aus als ob das an dem MTU-Mix liegt. Als Workaround wurde die MTU auf srv1 herabgesetzt. Damit sollte das problem für die Übergansphase gelöst sein.

Weiteres Feedback ist hier sehr willkommen.

**Comment by fooker** [comment]
Seems to work as update is done...
