### ISSUE TITLE
QoS auf den Gateways

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#89]
Per AGB drosseln unsere derzeitigen Gateway-Provider die Uplink-Bandbreite, falls ueber einen gewissen Zeitraum eine gewisse Bandbreite ueberschritten wird. Auf den Gateways sollten daher entsprechende QoS Regeln verwendet werden, um dies zu verhindern.

**Comment by fooker** [comment]
Instead of limiting the traffic we can add more gateways to have more traffic available.
