### ISSUE TITLE
Spendenmöglichkeiten

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#9]
Überarbeiten der Webseite -> Hinzufügen von Informationen zu zweckgebundenen Spenden.

Evtl. Nutzung von Spendenplattformen? Beispiele:
- https://www.betterplace.org/de/
- https://www.boost-project.com/de/

**Comment by SISheogorath** [comment]
Zumindest bei betterplace scheint es recht schnell und einfach zu gehen. Sollte man vielleicht am Freitag (24.07.2015) mal einrichten.

**Comment by reissmann** [comment]
Erfordert Gemeinnuetzigkeit

**Comment by mortzel** [comment]
Man könnte sich auch beim Amazon Partnerprogramm [1] anmeldung und die Links zu Produkten bei Amazon durch Partnerlinks ersetzt. Hierdurch würde man bei einem Kauf eines Produktes inerhalb von 24 nachdem die Person durch den Link auf Amazon gelandet ist eine Provision von 5% erhalten.
Ich würde auch meinen Account hierfür zur Verfügung stellen und das Geld dann an den Verein überweisen.

[1] https://partnernet.amazon.de/

**Comment by SISheogorath** [comment]
Wäre ich eher vorsichtig. Dann lieber Lokalen Firmen anbieten Werbung auf der Seite zu schalten und dafür eben Spenden bekommen. Quasi sowas wie "Ab einem Förderbeitrag von X€ im Jahr" bekommt man eine Werbeeinblendung auf der Webseite o.Ä.

Aber Amazon Advertising denke ich mal, haben wir A nicht nötig und B kommt bescheiden rüber.

**Comment by mortzel** [comment]
Nun ja, wir machen ja bereits Werbung für Amazon, da die Links zu den Preisen der Router [1] bereits auf Amazon verweisen. Daher würden wir nur diese Links ersetzten und nicht noch extra Werbung schalten.

[1] https://fulda.freifunk.net/anleitungen/einen-passenden-wlan-router-auswahlen/

**Comment by SISheogorath** [comment]
Okay, wenn wir nur diese Links austauschen, sehe ich da kein Problem, aber ich würde eben sehr ungern irgendwo ein Amazon Emblem hinpappen
