### ISSUE TITLE
First-Hop Redundanz

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#90]
Das Mesh-Netz funktioniert wunderbar dynamisch und kann schnell auf Aenderung der Verfuegbarkeit von Pfaden reagieren. Durch den fix zugewiesenen Default Gateway auf den Clients wird diese Dynamik gebrochen. Als Loesung bieten sich FHRP (mit Load-balancing) oder anycast an.

**Comment by SISheogorath** [comment]
ich würde in dem Fall irgendwie lieber einen anycast verwenden, da FHRP ja ein/mehrere GWs "standby" schalten würde. Allerdings habe ich keine wirkliche Idee, wie man einen anycast auf L2 verwirklicht. Zumindest nicht in verbindung mit Batman. (oder geht das einfach wie auf den Knoten mit einem neuen Interface mit entsprechender IP?).

Ich plane so oder so diesbezüglich mal Tests zu machen, falls noch keine Erfahrungen in diesem Bereich vorliegen. Bisher konnte ich nämlich keine Quellen finden, die das auf L2 erklärt haben.

**Comment by fooker** [comment]
Für Layer 2 könnte das hier interessant sein: http://www.open-mesh.org/projects/open-mesh/wiki/Connecting-Batman-adv-clouds

Für Ipv4 benötigt es auch noch einen Weg den State der Firewalls zu synchronisieren, da wir NAT machen müssen. Dafür könnte das hier interessant werden: http://conntrack-tools.netfilter.org/manual.html#settingup

**Comment by SISheogorath** [comment]
Solved my question by asking neoraider.

http://www.open-mesh.org/projects/open-mesh/wiki/Connecting-Batman-adv-clouds#Layer-2-Anycast

http://trier.freifunk.net/2015/10/21/layer-2-anycast-routing-mit-batman/

I'll setup a maschine to test and gice some feedback

**Comment by fooker** [comment]
Ist das nicht genau der selbe Link wie oben ;)
In den Kommentaren im zweiten Link wir das Problem des Syncs des NAT aufgegriffen, aber nicht gelöst.

**Comment by SISheogorath** [comment]
Ja, ist es, ich hatte die Seite noch offen und er hat den Kommentar nicht nachgeladen. 2 Minuten nach meinem Post kam auch die GitHub Mail an :/ tja :D so ist das...

Hilfreich ist da vielleicht https://en.wikipedia.org/wiki/Pfsync

**Comment by reissmann** [comment]
Wow, ich finde es ja super interessant, wie ausgerechnet in dieses issue so viel fahrt reinkommt. Ihr hattet mitbekommen, dass ich gesagt habe, dass ich das setup zuhause am laufen habe, oder?

**Comment by fooker** [comment]
Nein hatte ich nicht. Wie sieht denn das Setup genau aus?

**Comment by SISheogorath** [comment]
Ich auch nicht x.x

Allerdings wurde auch im Gluon Channel darüber gesprochen, ein Problem, welches wir auch nach der synchronisation der NAT Tabellen haben ist, dass plötzlich die IP Adressen wechseln dürften, wenn über das falsche GW die Anfragen rausfliegen. vielleicht müsste man hier künstlich spoofen?

**Comment by reissmann** [comment]
Zwei Gateways, jeweils ein Anycast MAC-VLAN Interface (wie in Trier), rumgefriemel an sysctl, Source-Routing fuer die Anycast Adresse und etwas Magic. 
Irgendwelche Dinge funktionieren und irgendwelche anderen Dinge nicht. Das Problem ist nicht nur das NAT auf den Gateways, sondern schon das ganze an sich irgendwie sinnvoll im Routing unterzukriegen. Und conntrackd ist leider auch echt keine gruene Wiese.

Die testing branch im saltstack-repo ist noch etwas labil und das anycast Zeugs nicht committed, da man dazu einige Skripte in salt anpacken muss. Aber man kriegt das recht schnell deployed. Wir koennen es auch gerne bei mir mal anschauen.

**Comment by SISheogorath** [comment]
Liebend gern, ich hätte sonst diese Woche mal einen Testsetup aufgebaut, aber wenn du den schon hast, vereinfacht das vieles. liegt der Testsetup bei dir in Hard- oder in Software rum?

**Comment by reissmann** [comment]
Aehh das Testsetup steht bei mir zur Zeit in Form von 4 virtuellen Maschinen rum. Wie gesagt, das ganze kann recht schnell aufgebaut werden. 
- Salt master installieren
- saltstack-repo auf den Salt master clonen und in die branch testing wechseln
- 2 Debian 8 (64bit) Systeme laut dieser Anleitung installieren: https://wiki.mag.lab.sh/wiki/Freifunk_Fulda/Gateway/Salt
- Saltstack die Magie tun lassen

Salt sollte ohne test=True laufen, da es sonst zu einer Reihe von Fehlern kommt, die in Wirklichkeit garnicht existieren. Beim ersten Durchlauf ist es gut moeglich, dass der Master in nen Timeout laeuft und dass man selbst von den Debian 8 Kisten disconnected wird, da Salt an der Netz-, Firewall- und SSH-Config bastelt. Idealerweise booted man die Kiste nach ca 10min mal durch und laesst danach Salt einfach nochmal laufen. Dann sollte alles passen.

Anschliessend muss man noch fastd Konfigurieren. Die Konfiguration der "echten" Backbone Systeme rausschmeissen und die der Testsysteme hinzufuegen (Keys stehen im fastd pillar).

Habt fun und berichtet ...

**Comment by SISheogorath** [comment]
Mal ein kleines Script, welches ips failovered, wenn ein GW den Gatewaymode nicht mehr annonced

Müsste mal getestet werden

```
#!/bin/bash


INTERFACE="bat0"


if [[ "${#}" -lt 3 ]]; then
        usage
        exit
fi

while getopts m:i:u:d: flag; do
        case ${flag} in
                m)
                        MACADDRESS="${OPTARG}"
                        ;;
                i)
                        INTERFACE="${OPTARG}"
                        ;;
                u)
                        UPEXECUTE="${OPTARG}"
                        ;;
                d)
                        DOWNEXECUTE="${OPTARG}"
                        ;;
                *)
                        exit
                        ;;
        esac
done


check() {
        if [[ `batctl -m ${INTERFACE} gwl | sed -e 's/(\s+)/|/g' | cut -d"|" -f4 | grep  ${MACADDRESS}| wc -l` -eq 0 ]];
        then
                ${UPEXECUTE}
        else
                ${DOWNEXECUTE}
        fi
}

# This part is for fun, if you consider shell scripts fun- and I do.
trap process_USR1 SIGUSR1

process_USR1() {
    echo 'Got signal USR1'
    exit 0
}
# End of fun. Now on to the business end of things.

me_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
me_FILE=$(basename $0)
cd /

if [ "$1" = "child" ] ; then   # 2. We are the child. We need to fork again.
    shift
    umask 0
    exec setsid $me_DIR/$me_FILE refork "$@" </dev/null >/dev/null 2>/dev/null &
    exit 0
fi
if [ "$1" != "refork" ] ; then # 1. This is where the original call starts.
    exec $me_DIR/$me_FILE child "$@" &
    exit 0
fi

                               # 3. We have been reforked. Go to work.
exec >/tmp/outfile
exec 2>/tmp/errfile
exec 0</dev/null

shift

                               # The real stuff goes here. To exit, see fun (above)
while true; do
    check
    sleep 10
done

exit # This will never run. Why is it here then? It's pretty.
     # Kind of like, "The End" at the end of a movie that you
     # already know is over. It's always nice.
```

**Comment by fooker** [comment]
As we don't have failover IPs and WAN links between gateways, this is not doable right now.
Batman should elect a new gateway if one goes down and one should receive a new DHCP lease with a new GW after a couple of seconds.
