### ISSUE TITLE
Split Internet and ICVPN Gateway

### ISSUE THREAD

**Issue by SISheogorath** [freifunk-fulda/orga#92]
Ich würde, sobald wir #90 gelöst haben, gerne die anycast adressen für ICVPN und Internet gateways trennen. @indigo423 hatte mich auf die Idee gebracht. Um aber dennoch das defaultgateway auf den Clients bei einer IP zu belassen, würde ich als Defaultgateway die nextnode Adresse verwendet und dort per Package die Routen hinterlegen, die für unseren Multli-Anycast-Setup notwendig wären. Somit würden zwar die Knoten dann selbstständig routen, aber eigentlich ist ja genau das letztendlich unser Ziel, die selbständigkeit der Knoten. Außerdem würden hierdurch die Aufgabenfelder etwas entzerrt und die Bereitstellung einzelner Dienste vereinfacht. (abgesehen vom NAT Problem).

Ich trug diese Ideen schon die ganze Woche mit mir rum, nur irgendwie kam ich am Freitag nicht dazu sie zu besprechen, naja, wir haben ja noch etwas Zeit ;)

**Comment by fooker** [comment]
Wie funktioniertt dabei der wechsel der Rückrouten bei einem Handover?

Wenn die Knoten selbstständig routen ist hier ggf. babel o.ä. die bessere Wahl als Mesh-Protokoll.

**Comment by reissmann** [comment]
Ich habe keine Ahnung wovon hier geredet wird. Anycast adressen für ICVPN und Internet gateways? What?

**Comment by SISheogorath** [comment]
@fooker Ich würde immernoch in einem L2 Mesh bleiben, das ich ja der Trick. Also weiterhin Batman nutzen. Dadurch übernimmt der Knoten nur eine Pseudo-Routing-Rolle.

Aber natürlich ist auch ein Wechsel des Routingprotokolls denkbar. Aber da bin ich noch nicht wirklich sicher, was sich da eigenen würde, da man sonst auch verteiltes DHCP bräuchte und Co, wenn man wirklich auf L3 wechseln würde.

@reissmann ganz ruhig, kein Stress es ist nur eine Idee. Wenn wir dir FHRP-Sache gelöst haben, habe ich nur schonmal Gedanken zum nächsten Schritt aufgeschreiben. ;)

**Comment by reissmann** [comment]
Ich verstehe immer noch nicht worum sich dieses issue ueberhaupt dreht. Irgendwas mit nextnode als default gateway und irgendwas mit ICVPN?

**Comment by SISheogorath** [comment]
Also im Grunde geht es ja darum, dass in Freifunk Internet ja eigentlich ein Service darstellt. Allerdings ist dieser durchaus an Gateways gebunden, da man nun auch ICVPN verwenden möchte, ist auch dieses irgendwie an das Gateway gebunden und nicht zuletzt der Zugriff über fastd ebenso. Ein Gateway-Server erfüllt also eigentlich _immer_ Die Rolle ICVPN Zugriff, Internetzugriff und internes Bridging. Und die Idee ist, wenn man es entzerren kann, diese Funktionen möglichst auseinander zu dröseln, sodass man z.B. ein ICVPN Gateway betreiben kann, ohne ein Internetgateway zu sein und zugleich auch allen Internettraffic an ein anderes Gateway weiterschieben muss.

Also zu ermöglichen, dass man Internet, ICVPN und generell erstmal fastd-access als wirklich eigenständige Dienste aufziehen kann, ohne dabei zusätzlich alle anderen Routen im auge behalten zu müssen. Das würde auch die Einstiegsschwelle ins Backend etwas absenken. So könnte man dann auf einem Server einen reinen ICVPN Setup fahren, ohne eine defaultroute zu einem anderen Gateway zu legen. In anderen Worten das Backend und dessen Setup stärker zu modularisieren.

Warum nun den Knoten als defaultgateway auf den Clients? Nun ja, defaultgateway ist nun mal erstmal 1 Adresse und um diese möglichst dezentral zu halten, auf dem Knoten. dieser nimmt dann ein Routing auf die entsprechende (zumindest in meinem Gedankenspiel) anycast adresse für die Gruppen ICVPN oder eben Internet vor. Dadurch haben die Clients immer das gleiche defaultgateway, aber die Daten fliegen eben direkt in richtung der richtigen Gateways ohne dass z.B. ein reines ICVPN Gateway Internet-Traffic hintenrum nochmal zu einem anderen Gateway schieben muss, welches ins Internet führt.

Aber wie gesagt, bisher ist es einfach nur eine Idee/ein Gedankenspiel

**Comment by reissmann** [comment]
Wie willst Du auf dem Knoten entscheiden, wohin Du routest, wenn es mehrere moegliche Gateways gibt? Du muesstest dann auf den Knoten ein Routingprotokoll haben, so dass die mit Internet-Gateways und IC-VPN Gateways routen tauschen koennen. Und muesstest ggf. relativ haeufig per Firmwareupgrade die Peers austauschen., oder?

**Comment by fooker** [comment]
Ich erwähnte babel ja bereits...

**Comment by reissmann** [comment]
In dem Falle sehe ich nicht, weshalb dieses Issue auf #90 dependen sollte. Wenn man zu babel wechselt und nextnode als Default Gateway verteilt, dann kann man aus meiner Sicht auf Anycast komplett verzichten.

**Comment by fooker** [comment]
Nope. See #143.
