### ISSUE TITLE
Neuer Anbieter für vServer

### ISSUE THREAD

**Issue by mortzel** [freifunk-fulda/orga#93]
Da über unsere Gateway-Server eine große Menge an Daten transportiert wird und meist jedes eingehende Bit auch wieder ausgeht, wird ein Anbieter benötigt, der diese Server nicht drosselt.

Hier eine mögliche Liste mit Anbietern:
- webtropia.com
  - 500 Mbit/s Traffic-Flat mit garantierten 100 Mbit/s
  - Keine Drosslung in den AGB zu sehen
- netcup.de
  - 1000 Mbit/s Traffic-Flat mit garantierten 200 Mbit/s
  - Drosslung nach dauerhaften Nutzung von mehr als 80 Mbit/s über 15 Minuten
- hosteurope.de
  - Peak-Bandbreite von 500 Mbit/s
  - Drosslung nach auf 100 Mbits/s dauerhaften Nutzung von mehr als 100 Mbit/s über eine Woche
- contabo.de
  - 100 Mbit/s Traffic-Flat 
  - Drosslung auf 10 Mbits/s nach dauerhaften Nutzung von mehr als 60 Mbit/s über 5 Tgae

**Comment by Moorviper** [comment]
Wobei es die Drosselung bei contabo nur bei den vservern gibt.
Bei Colocation gibts da keine Drosselung.

Kosten für einen Tower mit 2x 100mbit

Hier mal ein Vorschlag für ein setup:

Colo:
1 Towerstellplatz: 7,99
2x 100mbit port: 19,98
1 Strom Fix-Preis (100w): 19,99
1 eine weitere IP: 2€ (bin mir nicht sicher obs die wirklich braucht)

Macht monatlich : 49,96 €
Jährlich: 599,52€

Server: (Kriterien hohe Single-Core-Leistung und Stromverbrauch unter 100w nice2have 2x Gbit Lan Intel)

CPU: INTEL Core i3-6320 Box (3,9 GHz dualcore) 166€
Mainboard: ASRock H170M-ITX/DL Intel H170 So.1151 Dual Channel DDR4 Mini-ITX Retail
(2x Intel Gigabit Lan onboard) 94€
Ram: 8 oder 16 GB ddr4 45-95€
HDD: Western Digital 1000GB WD Red WD10EFRX 64MB 3.5 (8.9cm) SATA  62€

Strom-Versorgung:
pico-psu: PICOPSU-160-XT DC/DC (160 WATT) [24PL ATX] 50€
- Meanwell 100w netzteil
  https://www.elpro.org/de/leistung-120-watt-energy-star-v/35784-gs120a12-r7b.html 38€
- irgend ein billiges Case.
  Hab da noch welche am Dachboden stehen ...

Kosten:
Gesamt 455€ (8GB Variante) 
oder 505€ (16 GB Variante)

Darauf könnte man dann zB 2 Gateways laufen lassen

Zur Stromversorgung:
Eine Versorgung über eine Pico-psu erscheint erst mal teurer Aber spart einiges an Watt im vergleich zum herkömmlichen Schaltnetzteil.

Zum Vergleich mein Server:

Asrock Q1900m mit 8 GB ram 2x WD red + DD V6.5 dual DVB-S2 brauch idle 18w unter last max 24w
Mit einem ATX Netzteil kam ich auf 36-46W

**Comment by mortzel** [comment]
Das Problem mit Colo ist jedoch, dass bei einem Hardwareausfall jemand hinfahren muss und das Problem fixen muss. Daher sollten man bei einer Colo keine normale Desktop Hardware verwenden, sondern echte Server Hardware.

**Comment by mortzel** [comment]
Es wurde nun ein Root Server S bei Webtropia angemietet.
