### ISSUE TITLE
Meshviewer zeigt die Gateways nicht korrekt an

### ISSUE THREAD

**Issue by reissmann** [freifunk-fulda/orga#94]
"Insgesamt 113 Knoten, davon 82 online, 138 Clients, 0 Gateways".

Auf der Statistikseite werden allerdings die gewaehlten Gateways (per ID) angezeigt.

**Comment by SISheogorath** [comment]
Ich habe die Statistikseite korrigiert, wenn ich das richtig sehe, müssten wir auf den Gateways noch die Stati annoncen. Habe ich in Saltstack noch nicht gefunden.

Beispielhaft ist das in FFMW wie folgt gelöst:
https://gluon-gateway-doku.readthedocs.org/de/latest/configuration/daemons/alfred.html#konfiguration

Wir sollten (glaub ich) also bei uns auch mal https://github.com/ffnord/ffnord-alfred-announce klonen und in regelmäßig abständen annoncen, oder?

Momentan horchen wir auf den Gateways eigentlich nur, wenn ich das richtig sehe.

**Comment by fooker** [comment]
Ich hatte damit schon mal angefangen. Guck dir mal alfred-announce und alfred-facts in github an.

Alternativ kannst du auch die Werte für die GWs in die aliases des map-backend eintragen.

## 

-----Original Message-----

**Comment by fooker** [comment]
fixed.
