### ISSUE TITLE
The config page should propose including the PLZ into the hostname

### ISSUE THREAD

**Issue by fooker** [freifunk-fulda/orga#99]
The hostname section in the config mode should be change in a way that it's proposing to include the PLZ of the node in the hostname.

Therefore the default hostname prefix should be changed and a approperiate info text should be added.

**Comment by reissmann** [comment]
Why?

**Comment by fooker** [comment]
To find clusters of nodes in dedicated areas and have a group-by-gemeinde in node lists.

**Comment by mortzel** [comment]
How is the actual opinion on this ?

**Comment by fooker** [comment]
Nice to have, hard to enforce, broken on mobile nodes, impossible to apply to nodes afterwards.

## 

-----Original Message-----

**Comment by mortzel** [comment]
So close the issue as "won't fix" ?

**Comment by fooker** [comment]
I don't think we can fix this.
